### DISCUSSION TITLE
🐞 Error with mounted ca-certificates in Kubernetes

### DISCUSSION THREAD

**Discussion by MikaelElkiaer** [dagger/dagger#12200] [Help]
### What is the issue?

I see the error:

`time="2024-10-04T08:35:43Z" level=warning msg="failed to rehash ca-certificates: ERROR: Access denied '/usr/local/share/ca-certificates'\n" error="exit status 2"`

When I mount a configmap containing `some-ca.crt` into the folder.
It does not crash the dagger-engine, which starts up afterwards.

While it does not work following container restart, if I exec `update-ca-certificates` in a pod the CA certificate is applied and works as expected.

### Dagger version

0.13.3 (Helm chart)

### Steps to reproduce

1. Create ConfigMap, e.g.:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-ca-certificates
  namespace: dagger
data:
  some-ca.crt: |
    -----BEGIN CERTIFICATE-----
    <content>
    -----END CERTIFICATE-----
```

2. Install Dagger via Helm (I do this via FluxCD):

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dagger
  namespace: dagger
spec:
  interval: 10m0s
  chart:
    spec:
      chart: dagger-helm
      version: 0.13.3
      sourceRef:
        kind: HelmRepository
        name: dagger
        namespace: flux-system
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: DaemonSet
              name: dagger-dagger-helm-engine
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  mountPath: /usr/local/share/ca-certificates/
                  name: additional-ca-certificates
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: additional-ca-certificates
                  configMap:
                    name: additional-ca-certificates
  timeout: 20m
  values:
```

### Log output

`time="2024-10-04T08:35:43Z" level=warning msg="failed to rehash ca-certificates: ERROR: Access denied '/usr/local/share/ca-certificates'\n" error="exit status 2"`
