### DISCUSSION TITLE
🐞 Dagger panics when running in CircleCI pipeline

### DISCUSSION THREAD

**Discussion by MarcosRolando** [dagger/dagger#12344] [Help]
### What is the issue?

I'm migrating my CI from GH actions to CircleCI in order to use ARM executors. Following is the pipeline for both GH Actions and CircleCI. I'm using the Dagger Python SDK. GH Actions pipeline runs fine, but CircleCI instantly panics when the dagger run command is executed.

Funnily enough, when SSHing into the CircleCI instance and running the same command there, the engine Dagger pipeline works just fine. I could not for the life of me find a related issue, and the documentation does not specify any workarounds as far as I could see. This fails for both docker and machine executors.

GH Action workflow:

```
jobs:
  dockerhub:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'
      - 
        name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY_PROTOBUF_REPO }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      -
        name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
      -
        name: Install Dagger Python SDK
        run: pip install -r requirements.txt
      -
        name: Release and deploy with Dagger
        run: dagger run python .dagger/build.py
        env:
          DOCKER_USER: ${{ vars.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_REPO: ${{ vars.DOCKER_REPO }}
```

CircleCI workflow:

```
version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - dockerhub-deploy:
          filters:
            branches:
              only:
                - main

jobs:
  dockerhub-deploy:
    docker:
      - image: cimg/python:3.12.2
    environment:
      CIRCLE_PIPELINE_NUMBER: << pipeline.number >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set up SSH keys
          command: |
            mkdir -p ~/.ssh/
            echo "${SSH_PRIVATE_KEY_PROTOBUF_REPO}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Install Dagger CLI
          command: curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
      - run:
          name: Install Dagger Python SDK
          command: pip install -r requirements.txt
      - run:
          name: Release and deploy with Dagger
          command: $HOME/.local/bin/dagger run python .dagger/build.py
```

Error generated:

```
[?1002h[?25l[2K[?25h[?1002l[?1003l[?1006lCaught panic:

runtime error: slice bounds out of range [3:1]

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:478 +0x91
panic({0x12ba680?, 0xc0003c21e0?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/charmbracelet/bubbles/viewport.Model.visibleLines(...)
	/go/pkg/mod/github.com/charmbracelet/bubbles@v0.18.0/viewport/viewport.go:123
github.com/charmbracelet/bubbles/viewport.(*Model).GotoBottom(0xc000318048?)
	/go/pkg/mod/github.com/charmbracelet/bubbles@v0.18.0/viewport/viewport.go:237 +0x17b
github.com/vito/progrock.(*Model).render(0xc000318000)
	/go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/model.go:452 +0x275
github.com/vito/progrock.(*Model).Update(0xc000318000, {0x1241600?, 0xc000130750?})
	/go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/model.go:357 +0xa5
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc00044a410, {0x15456e0?, 0xc000318000?}, 0x100?)
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:411 +0x75a
github.com/charmbracelet/bubbletea.(*Program).Run(0xc00044a410)
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:543 +0x86e
github.com/vito/progrock.(*UI).Run(0x1223300?, {0x154b0a8, 0x1f1bda0}, 0x4c9020?, 0x1f1cae0?)
	/go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/model.go:215 +0x56a
main.legacyTUI({0x154b0a8, 0x1f1bda0}, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc000492270, 0x24}, {0xc0004922a0, ...}, ...}, ...)
	/app/cmd/dagger/engine.go:154 +0x19d
main.withEngineAndTUI({0x154b0a8, 0x1f1bda0}, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc000492270, 0x24}, {0xc0004922a0, ...}, ...}, ...)
	/app/cmd/dagger/engine.go:83 +0x158
main.run({0x154b0a8, 0x1f1bda0}, {0xc00005cd80, 0x2, 0x2})
	/app/cmd/dagger/run.go:100 +0x22b
main.Run(0x1ed8fc0?, {0xc00005cd80?, 0x4?, 0x136ff9b?})
	/app/cmd/dagger/run.go:76 +0x33
github.com/spf13/cobra.(*Command).execute(0x1ed8fc0, {0xc00005cd40, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x1ed78c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/app/cmd/dagger/main.go:145 +0x2c
[32m█[0m [33m[0.00s][0m connect
[32m┻[0m 

[33m⧗[0m [1m0.00s[0m [33m⣾[0m [1m1[0m [90m • [0m[1mconnect[0m
```

![image](https://github.com/dagger/dagger/assets/50052015/f78c670b-9a53-4fc7-a7d4-de02e3b0e3f7)

### Dagger version

dagger v0.10.2 (registry.dagger.io/engine) linux/amd64

### Steps to reproduce

Create a circleci workflow that executes a Python SDK Dagger pipeline. This fails before executing any of the Python pipeline code.

### Log output

caught panic:

runtime error: slice bounds out of range [3:1]

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:478 +0x91
panic({0x12ba680?, 0xc0003c21e0?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/charmbracelet/bubbles/viewport.Model.visibleLines(...)
        /go/pkg/mod/github.com/charmbracelet/bubbles@v0.18.0/viewport/viewport.go:123
github.com/charmbracelet/bubbles/viewport.(*Model).GotoBottom(0xc000318048?)
        /go/pkg/mod/github.com/charmbracelet/bubbles@v0.18.0/viewport/viewport.go:237 +0x17b
github.com/vito/progrock.(*Model).render(0xc000318000)
        /go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/model.go:452 +0x275
github.com/vito/progrock.(*Model).Update(0xc000318000, {0x1241600?, 0xc000130750?})
        /go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/model.go:357 +0xa5
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc00044a410, {0x15456e0?, 0xc000318000?}, 0x100?)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:411 +0x75a
github.com/charmbracelet/bubbletea.(*Program).Run(0xc00044a410)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:543 +0x86e
github.com/vito/progrock.(*UI).Run(0x1223300?, {0x154b0a8, 0x1f1bda0}, 0x4c9020?, 0x1f1cae0?)
        /go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/model.go:215 +0x56a
main.legacyTUI({0x154b0a8, 0x1f1bda0}, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc000492270, 0x24}, {0xc0004922a0, ...}, ...}, ...)
        /app/cmd/dagger/engine.go:154 +0x19d
main.withEngineAndTUI({0x154b0a8, 0x1f1bda0}, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc000492270, 0x24}, {0xc0004922a0, ...}, ...}, ...)
        /app/cmd/dagger/engine.go:83 +0x158
main.run({0x154b0a8, 0x1f1bda0}, {0xc00005cd80, 0x2, 0x2})
        /app/cmd/dagger/run.go:100 +0x22b
main.Run(0x1ed8fc0?, {0xc00005cd80?, 0x4?, 0x136ff9b?})
        /app/cmd/dagger/run.go:76 +0x33
github.com/spf13/cobra.(*Command).execute(0x1ed8fc0, {0xc00005cd40, 0x2, 0x2})
        /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x1ed78c0)
        /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /app/cmd/dagger/main.go:145 +0x2c
█ [0.00s] connect
┻ 

⧗ 0.00s ⣾ 1  • connect
