### DISCUSSION TITLE
GCR second private image pull throws 403 Forbidden

### DISCUSSION THREAD

**Discussion by PumpkinSeed** [dagger/dagger#12419] [Help]
### What is the issue?

I have two private images on `gcr.io` which necessary for run the e2e tests in our system. I created a service account which has permission to pull these images and I created a json key. We are using bitbucket pipelines at the moment and I can pull these images in a way like this:
```
 services:
    ....
    vault:
      image:
        name: gcr.io/company/vault:latest
        username: _json_key
        password: '$GCR_IMAGE_PULLER_KEY'
    couchbase:
      image:
        name: gcr.io/company/couchbase:7.1.3
        username: _json_key
        password: '$GCR_IMAGE_PULLER_KEY'
      memory: 8192
```
This works just fine, it can pull the images by using the same key I just created with the service account. 

---
I wanted to create the same behavior with Dagger's Go SDK like this:
```
secretForCouchbase := client.SetSecret("secretForCouchbase", key)
couchbase, err := client.Container().
    From("gcr.io/company/couchbase:7.1.3").
    WithRegistryAuth("gcr.io", "_json_key", secretForCouchbase).
    WithExposedPort(8091).
    AsService().Start(ctx)

secretForVault := client.SetSecret("secretForVault", key)
vault, err := client.Container().
    From("gcr.io/company/vault:latest").
    WithRegistryAuth("gcr.io", "_json_key", secretForVault).
    WithExposedPort(8200).
    AsService().Start(ctx)
```
The key is the same JSON key for the service account I used in bitbucket pipeline's services. 

It always pulls the first image properly, but the second run into an error of `ERROR: unexpected status from HEAD request to https://gcr.io/v2/company/vault/manifests/latest: 403 Forbidden`. If I change to order of the images (so the couchbase will be the next, it will fail on the same way), so I can make sure that the issue is not on the side of pulling images, because even Dagger could pull both of the images. 

So Dagger pulls the first image (no matters it is vault or couchbase) properly and fails on the second one. 

### Log output

41: resolve image config for gcr.io/company/vault:latest
41: > in from gcr.io/company/vault:latest
41: resolve image config for gcr.io/company/vault:latest ERROR: unexpected status from HEAD request to https://gcr.io/v2/company/vault/manifests/latest: 403 Forbidden

### Steps to reproduce

1. Add private images to `gcr.io`, and create a service account with a key which has permission to pull those images.
2. Create a code from above which wants to use the two images as services.
3. Run it so the script tries to pull those images.

### SDK version

Go SDK v0.9.3

### OS version

5.15.133-1-MANJARO
