### DISCUSSION TITLE
[Question] How to use Buildkit in Github Action?

### DISCUSSION THREAD

**Discussion by hongchaodeng** [dagger/dagger#2082] [General]
Currently the dagger Github Action can install `dagger` binary:

```yaml
    - name: Install Dagger
      uses: dagger/dagger-action@v1
      with:
        install-only: true
```

But running `dagger up` in Action will fail for any buildkit operations. For example:

```
patchGrafana: {=

	#up: [
		op.#Load & {
			from: kubernetes.#Kubectl & {
				version: "v1.23.3"
			}
		},
		...
		op.#Exec & {
			always: true
			args: [
				"/bin/bash",
				"--noprofile",
				"--norc",
				"-eo",
				"pipefail",
				"/entrypoint.sh",
			]
			env: KUBECONFIG: "/kubeconfig"
		},
	]
}
```

It will failed:

```
{"level":"error","environment":"test","task":"patchGrafana","task":"patchGrafana","duration":17211.67983,"error":"process \"/bin/bash --noprofile --norc -eo pipefail /entrypoint.sh\" did not complete successfully: exit code: 1","state":"failed","time":"2022-02-11T07:13:21Z","time":"2022-02-11T07:13:21Z","caller":"/home/runner/work/dagger/dagger/environment/pipeline.go:162","message":"failed"}
```

**Comment by grouville** [comment]
Hi @hongchaodeng,
Does this config work locally ? Can you please show us what is inside the `/entrypoint.sh` ?

Dagger always stops when a command has a return code != 0 (we have issues working on some fixes)

**Comment by grouville** [comment]
Here is a working example.

_Some things to consider:_
You need to set your SOPS key as a Github secret, for the action to be able to decrypt your `dagger.#Secret`.

That's what I do in the below code: `secrets.DAGGER_AGE_KEY`. This key lies inside the `~/.config/dagger/keys.txt` file.
You also need to pass an arg: _which dagger command do you want to run_ ?

```
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Dagger
        uses: dagger/dagger-action@v1
        with:
          age-key: ${{ secrets.DAGGER_AGE_KEY }}
          args: up -e ci
```
