### ISSUE TITLE
Default helm chart installation has an odd volume path

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#10277]
When installing the official Dagger helm chart following the docs here https://docs.dagger.io/ci/integrations/kubernetes/#example, the resulting `volume` paths seem to contain the `dagger` word a bit too much:

```
        serviceAccountName: default
        terminationGracePeriodSeconds: 300
        volumes:
        - hostPath:
            path: /var/lib/dagger-dagger-dagger-helm
            type: ""
          name: varlibdagger
        - hostPath:
            path: /run/dagger-dagger-dagger-helm
            type: ""
          name: varrundagger
    updateStrategy:
```

 We should fix this as well as updating the other places in our docs like the Gitlab and Tekton guides which  reference the use of this volume.
