### ISSUE TITLE
[Feature] docker.#Build supports source path string input

### ISSUE THREAD

**Issue by hongchaodeng** [dagger/dagger#1488]
Currently docker.#Build can only be **manually** input via `dagger input dir $path` command.

This is not possible to parse entire yaml as value as follows:

```yaml
build:
  source: .
  push:
    target: ghcr.io/hongchaodeng/ai-demo
```

It would be great to support source path string input.
