### ISSUE TITLE
[Question] How to use Buildkit in Github Action?

### ISSUE THREAD

**Issue by hongchaodeng** [dagger/dagger#1599]
Currently the dagger Github Action can install `dagger` binary:

```yaml
    - name: Install Dagger
      uses: dagger/dagger-action@v1
      with:
        install-only: true
```

But running `dagger up` in Action will fail for any buildkit operations. For example:

```
patchGrafana: {=

	#up: [
		op.#Load & {
			from: kubernetes.#Kubectl & {
				version: "v1.23.3"
			}
		},
		...
		op.#Exec & {
			always: true
			args: [
				"/bin/bash",
				"--noprofile",
				"--norc",
				"-eo",
				"pipefail",
				"/entrypoint.sh",
			]
			env: KUBECONFIG: "/kubeconfig"
		},
	]
}
```

It will failed:

```
{"level":"error","environment":"test","task":"patchGrafana","task":"patchGrafana","duration":17211.67983,"error":"process \"/bin/bash --noprofile --norc -eo pipefail /entrypoint.sh\" did not complete successfully: exit code: 1","state":"failed","time":"2022-02-11T07:13:21Z","time":"2022-02-11T07:13:21Z","caller":"/home/runner/work/dagger/dagger/environment/pipeline.go:162","message":"failed"}
```
