### ISSUE TITLE
Deploying to Netlify through GH Actions fails with 404 

### ISSUE THREAD

**Issue by mreferre** [dagger/dagger#1968]
### What is the issue?

Hey there. I am trying to deploy to Netlify using the tutorial (Integrating with your CI environment). I am testing GH Actions but I am receiving the error message below. I am unclear what's not finding when communicating to Netlify (?)

I am not super familiar with Netlify but I have created the `NETLIFY_TOKEN` secrets and used `massimo` as a `NETLIFY_TEAM` (because that's my team name on Netlify). I am using the free tier, FYI. 

### Log output

```
.......
......
3:07PM INF actions.build.run._exec | #20 10.45 Compiled successfully.
3:07PM INF actions.build.run._exec | #20 10.45
3:07PM INF actions.build.run._exec | #20 10.46 File sizes after gzip:
3:07PM INF actions.build.run._exec | #20 10.46
3:07PM INF actions.build.run._exec | #20 10.47   40.12 KB  build/static/js/2.42cb4ad1.chunk.js
3:07PM INF actions.build.run._exec | #20 10.47   1.54 KB   build/static/js/main.8ce0b0b2.chunk.js
3:07PM INF actions.build.run._exec | #20 10.47   1.46 KB   build/static/css/main.9149988f.chunk.css
3:07PM INF actions.build.run._exec | #20 10.47   782 B     build/static/js/runtime-main.58186263.js
3:07PM INF actions.build.run._exec | #20 10.47
3:07PM INF actions.build.run._exec | #20 10.47 The project was built assuming it is hosted at ./.
3:07PM INF actions.build.run._exec | #20 10.47 You can control this with the homepage field in your package.json.
3:07PM INF actions.build.run._exec | #20 10.47
3:07PM INF actions.build.run._exec | #20 10.47 The build folder is ready to be deployed.
3:07PM INF actions.build.run._exec | #20 10.47
3:07PM INF actions.build.run._exec | #20 10.47 Find out more about deployment here:
3:07PM INF actions.build.run._exec | #20 10.47
3:07PM INF actions.build.run._exec | #20 10.47   bit.ly/CRA-deploy
3:07PM INF actions.build.run._exec | #20 10.47
3:07PM INF actions.build.run._exec | #20 10.50 Done in 10.23s.
3:07PM INF actions.deploy.container._exec | #22 0.749 curl: (22) T
3:07PM ERR actions.deploy.container._exec | failed: process "bash --norc -e -o pipefail /bash/scripts/deploy.sh" did not complete successfully: exit code: 1
    duration=800ms
3:07PM INF actions.deploy.container._exec | he requested URL returned error: 404
3:07PM INF actions.deploy.container._exec | #22 0.754 Error creating site [todoapp-dagger-europa] for account [massimo]
3:07PM INF actions.deploy.container._exec | #22 0.754 {"code":404,"message":"Not Found"}
3:07PM FTL system | failed to execute plan: task failed: actions.deploy.container._exec: process "bash --norc -e -o pipefail /bash/scripts/deploy.sh" did not complete successfully: exit code: 1


Error: The process '/opt/hostedtoolcache/dagger/0.2.4/x64/dagger' failed with exit code 1
```

### Steps to reproduce

I have simply forked the `dagger/dagger` repo and replaced the `todoapp.yaml` file in the repo (an old version?) with the one you have in the tutorial (which seems newer). 

This is how my todoapp.yaml file looks like: 
```
name: todoapp

on:
  push:
    # Trigger this workflow only on commits pushed to the main branch
    branches:
      - main

# Dagger plan gets configured via client environment variables
env:
  # This needs to be unique across all of netlify.app
  APP_NAME: todoapp-dagger-europa
  NETLIFY_TEAM: massimo
  # Get one from https://app.netlify.com/user/applications/personal
  NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
  # GitHub Actions friendly logs
  DAGGER_LOG_FORMAT: plain

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Deploy to Netlify
        uses: dagger/dagger-for-github@v2
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          workdir: pkg/universe.dagger.io/examples/todoapp
          args: do deploy
```

### Dagger version

what the GH Actions installs (latest?) 

### OS version

What the GH Actions file specifies (Ubuntu)
