### ISSUE TITLE
To improve GitHub actions integration documentation 

### ISSUE THREAD

**Issue by vklimontovich** [dagger/dagger#2160]
### What is the issue?

If I'd follow [GitHub integration manual](https://docs.dagger.io/1201/ci-environment) as-is, I'm going to get following error: `failed to load plan: dagger project not found. Run `dagger project init`. That's because `cue.mod` is not there. 

I think the documentation should give either recommendation to commit `cue.mod` to git (is it a good idea?), or explicitly offer run init & update as part of GitHub workflow:

```
     - name: Init dagger (dagger project init)
        uses: dagger/dagger-for-github@v2
        with:
          args: project init

      - name: Update dagger (dagger project update)
        uses: dagger/dagger-for-github@v2
        with:
          args: project update

      - name: Build with dagger (dagger do build)
         uses: dagger/dagger-for-github@v2
         with:
           args: do build
```

In fact, explicit advice whether to put `cue.mod` to git would be nice
