### ISSUE TITLE
🐞 Go container pull default image

### ISSUE THREAD

**Issue by guiyomh** [dagger/dagger#2209]
### What is the issue?

I have overridden the go image used by the `go.#Test` action, to use a custom private image. Like this:

```cue
go.#Test & {
	package: "./..."
	source:  _source
	go.#Container & {
		input: _goImage.output
		command: {
			flags: {
				"-count": "1"
				"-race":  true
			}
		}
	}
}
```
But when I execute my action, the official hub image is still pulled.

And this is a problem for me on gitlab because I reach the docker hub quota faster. And I think it would be more efficient not to pull that image and do nothing with it.

### Log output

```
12:37PM DBG actions.test._image._dag."0"._op | 
12:37PM DBG actions.test._image._dag."0"._op | #1 load metadata for docker.io/library/golang:1.18-alpine
12:37PM DBG actions.test._image._dag."0"._op | #1 sha256:5ab389a9ce7d05dd73e1c3fac09e560b8a5245b53f199de5e69e11d6a380af08
12:37PM DBG actions.test._image._dag."0"._op | #1 DONE 0.5s
12:37PM DBG actions.test._image._dag."0"._op | 
12:37PM DBG actions.test._image._dag."0"._op | #4 Pull index.docker.io/golang:1.18-alpine
12:37PM DBG actions.test._image._dag."0"._op | #4 sha256:6ad4b59c0daf29a30ff85e5bf62be65d35d342833e759e6ed905143199945326
12:37PM DBG actions.test._image._dag."0"._op | #4 resolve docker.io/library/golang:1.18-alpine
12:37PM DBG actions.test._image._dag."0"._op | #4 resolve docker.io/library/golang:1.18-alpine 0.2s done
12:37PM DBG actions.test._image._dag."0"._op | #4 DONE 0.2s
```

### Steps to reproduce

I have create this plan:

```cue
package ci

import (
	"dagger.io/dagger"
	"universe.dagger.io/go"
	"universe.dagger.io/docker"
)

dagger.#Plan & {
	client: filesystem: ".": read: contents: dagger.#FS
	client: commands: ecrPassword: {
		name: "aws"
		args: ["ecr", "get-login-password", "--region", "eu-west-3"]
		stdout: dagger.#Secret
	}
	actions: {

		_source: client.filesystem["."].read.contents

		_goImage: docker.#Pull & {
			source: "<aws-id>.dkr.ecr.<aws-region>.amazonaws.com/public/library/golang:1.18-buster"
			auth: {
				username: "AWS"
				secret:   client.commands.ecrPassword.stdout
			}
		}

		// Run unit test
		test: go.#Test & {
			package: "./..."
			source:  _source
			go.#Container & {
				input: _goImage.output
				command: {
					flags: {
						"-count": "1"
						"-race":  true
					}
				}
			}
		}
	}
}

```

And I run it with `dagger do test --log-format=plain -l debug

### Dagger version

dagger 0.2.5 (7d2f279c) darwin/amd64

### OS version

macOS 12.2.1

**Comment by grouville** [comment]
cc @dolanor

**Comment by dolanor** [comment]
It's interesting. It seems that the engine will use the base go alpine image before getting the `_goImage`
I guess we guess the initalization wrong at this level. Or maybe, we need the base image to be able to compute more.

I think @aluzzardi might know more.

`my log`
```
1:40PM DBG system | detected buildkit config    haveHostNetwork=true isActive=true version=v0.10.1
1:40PM DBG system | platform detected automatically    platform={amd64 linux  [] }
1:40PM DBG system | spawning buildkit job    attrs=null localdirs={
    "/home/dolanor/tmp/manomano-custom-img": "/home/dolanor/tmp/manomano-custom-img"
}
1:40PM INF actions.test._image._dag."0"._op | computing
1:40PM INF actions._goImage._op | computing
1:40PM INF client.filesystem.".".read | computing
1:40PM DBG client.filesystem.".".read | loading local directory    path=/home/dolanor/tmp/manomano-custom-img
1:40PM INF client.filesystem.".".read | completed    duration=0s
1:40PM DBG client.filesystem.".".read | merging task result    result={
    contents: {
        $dagger: {
            fs: {}
        }
    }
}
1:40PM DBG client.filesystem.".".read | #3 Local /home/dolanor/tmp/manomano-custom-img
1:40PM DBG client.filesystem.".".read | #3 sha256:a8a95a67a61eb6c87315cf08dde85e7438467b9ab57530e512129018bb0e9210
1:40PM DBG client.filesystem.".".read | #3 transferring /home/dolanor/tmp/manomano-custom-img: 10.91kB done
1:40PM DBG client.filesystem.".".read | #3 DONE 0.0s
1:40PM DBG client.filesystem.".".read | 
1:40PM DBG client.filesystem.".".read | #4 Local /home/dolanor/tmp/manomano-custom-img [copy]
1:40PM DBG client.filesystem.".".read | #4 sha256:992307082bb220c0fd649b445784a5b558c07d068bd014c66434efd567de1048
1:40PM DBG client.filesystem.".".read | #4 CACHED
1:40PM DBG actions.test._image._dag."0"._op | 
1:40PM DBG actions.test._image._dag."0"._op | #2 load metadata for docker.io/library/golang:1.18-alpine
1:40PM DBG actions.test._image._dag."0"._op | #2 sha256:5ab389a9ce7d05dd73e1c3fac09e560b8a5245b53f199de5e69e11d6a380af08
1:40PM INF actions._goImage._op | completed    duration=200ms
1:40PM DBG actions._goImage._op | merging task result    result={
    output: {
        $dagger: {
            fs: {}
        }
    }
    digest: "sha256:7a2940e604e0e9dff114d7f432bb4109968736fa26dfbf3346c01ce3fe6ee404"
    config: {
        env: {
            GOLANG_VERSION: "1.12.7"
            GOPATH:         "/go"
            PATH:           "/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        }
        cmd: ["bash"]
        workdir: "/go"
        label: {}
        argsescaped: true
        onbuild: []
    }
}
1:40PM DBG actions._goImage._op | #2 ...
1:40PM DBG actions._goImage._op | 
1:40PM DBG actions._goImage._op | #1 load metadata for my.custom.com/build-image:latest
1:40PM DBG actions._goImage._op | #1 sha256:df8731cab029b9c1c948470885e0dc061ecf41d9dd58e87cd2dd97077007c5e7
1:40PM DBG actions._goImage._op | #1 DONE 0.1s
1:40PM DBG actions._goImage._op | 
1:40PM DBG actions._goImage._op | #5 Pull my.custom.com/build-image
1:40PM DBG actions._goImage._op | #5 sha256:e9065412ed8567b95707d8e8adcfaa618ffd5e7dfbf97d726fecc5218a42ca29
1:40PM DBG actions._goImage._op | #5 resolve my.custom.com/build-image:latest 0.0s done
1:40PM DBG actions._goImage._op | #5 DONE 0.0s
1:40PM DBG actions.test._image._dag."0"._op | 
1:40PM DBG actions.test._image._dag."0"._op | #2 load metadata for docker.io/library/golang:1.18-alpine
1:40PM DBG actions.test._image._dag."0"._op | #2 sha256:5ab389a9ce7d05dd73e1c3fac09e560b8a5245b53f199de5e69e11d6a380af08
1:40PM DBG actions.test._image._dag."0"._op | #2 DONE 0.6s
1:40PM DBG actions.test._image._dag."0"._op | 
1:40PM DBG actions.test._image._dag."0"._op | #6 Pull index.docker.io/golang:1.18-alpine
1:40PM DBG actions.test._image._dag."0"._op | #6 sha256:6ad4b59c0daf29a30ff85e5bf62be65d35d342833e759e6ed905143199945326
1:40PM DBG actions.test._image._dag."0"._op | #6 resolve docker.io/library/golang:1.18-alpine
1:40PM INF actions.test._image._dag."0"._op | completed    duration=900ms
1:40PM DBG actions.test._image._dag."0"._op | merging task result    result={
    output: {
        $dagger: {
            fs: {}
        }
    }
    digest: "sha256:42d35674864fbb577594b60b84ddfba1be52b4d4298c961b46ba95e9fb4712e8"
    config: {
        env: {
            GOLANG_VERSION: "1.18.1"
            GOPATH:         "/go"
            PATH:           "/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        }
        cmd: ["/bin/sh"]
        workdir: "/go"
    }
}
1:40PM INF actions.test._image._dag."1"._exec | computing
1:40PM DBG actions.test._image._dag."1"._exec | dependency detected    dependency=actions.test._image._dag."0"._op
1:40PM INF actions.test._image._dag."1"._exec | completed    duration=0s
1:40PM DBG actions.test._image._dag."1"._exec | merging task result    result={
    output: {
        $dagger: {
            fs: {}
        }
    }
    exit: 0
}
1:40PM DBG actions.test._image._dag."0"._op | #6 resolve docker.io/library/golang:1.18-alpine 0.2s done
1:40PM DBG actions.test._image._dag."0"._op | #6 CACHED
1:40PM DBG actions.test._image._dag."1"._exec | 
1:40PM DBG actions.test._image._dag."1"._exec | #7 Exec ["apk", "-U", "--no-cache", "add", "git"]
1:40PM DBG actions.test._image._dag."1"._exec | #7 sha256:d694788c3995cf59182b3a6fb6039af0fd7d6a609a9a851df59a7feca6cbe804
1:40PM DBG actions.test._image._dag."1"._exec | #7 CACHED
1:40PM INF actions.test._exec | computing
1:40PM DBG actions.test._exec | dependency detected    dependency=actions._goImage._op
1:40PM DBG actions.test._exec | dependency detected    dependency=actions.test._image._dag."0"._op
1:40PM DBG actions.test._exec | dependency detected    dependency=actions.test._image._dag."1"._exec
1:40PM DBG actions.test._exec | dependency detected    dependency=client.filesystem.".".read
1:40PM DBG actions._goImage._op | 
1:40PM DBG actions._goImage._op | #5 Pull my.custom.com/build-image
1:40PM DBG actions._goImage._op | #5 sha256:e9065412ed8567b95707d8e8adcfaa618ffd5e7dfbf97d726fecc5218a42ca29
```

**Comment by guiyomh** [comment]
In `go/container.cue` we have this:

```cue
#Container: {
	// ...

	// Use go image
	_image: #Image

        // ...

	docker.#Run & {
		input:   *_image.output | docker.#Image
		
        // ...
        }
}
```

To customize the image I override the `Container.input`, but `_image` remains. So, even if I override the `Container.input`, `_image` is pull before run the container.

**Comment by guiyomh** [comment]
Maybe we must replace `_image` with `image`, and instead of overriding` Container.input`, I will override `Container.image`

**Comment by nipuna-perera** [comment]
Pardon my lack of cue knowledge, but would it work if the `_image` and `docker.#Image` were swapped? Like

```cue
docker.#Run & {
   input:  docker.#Image | *_image.output 
// ...
}
```
Would it then give priority to `docker.#Image?` or does it not matter?

**Comment by guiyomh** [comment]
@nipuna-perera I will try it.

@dolanor and @grouville I think, I have the same with `yarn.#Run`. With a small variation, I have the impression that my custom image is not used (it's still the default image).

```cue
test: yarn.#Run & {
			source: client.filesystem.".".read.contents
			container: #input: _nodeImage.output
			script:   "test"
			buildDir: "build"
		}
```

**Comment by TomChv** [comment]
That's strange :O I'll work on this one

**Comment by TomChv** [comment]
That's weird, the official example works : https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/go/test/container.cue#L21 :/

**Comment by guiyomh** [comment]
Do you have some news about the fix?
I reproduce it with the dagger 0.2.36.
I have a action defininition like this:

```yaml
package markdown

import (
    "dagger.io/dagger"
    "universe.dagger.io/docker"
)

#Lint: {
    // source code
    source: dagger.#FS

    // mardownlint version
    version: *"0.31.1" | string

    // Files to lint
    files: [...string]

    docker.#Run & {
        input: *_image.output | _
        _image: docker.#Pull & {
            source: "tmknom/markdownlint:\(version)"
        }
        mounts: "source": {
            dest:     "/src"
            contents: source
        }
        workdir: "/src"
        command: {
            name: "markdownlint"
            args: files
        }
    }
}
```

and in my plan I do something like this, to use a custom image: 
```yaml

        _image: {
            markdownlint: docker.#Pull & {
                source: "\(_#DefaultAwsAccount).dkr.ecr.\(_#DefaultAwsRegion).amazonaws.com/my/markdownlint:0.31.1-custom"
                auth: {
                    username: "AWS"
                    secret:  client.commands.ecrPassword.stdout
                }
            }
        }
        // Lint the project
        lint: {

            // Lint markdown file
            "markdown": markdown.#Lint & {
                input: _image.markdownlint.output
                source: _source.output
                files: ["README.md"]
            }
        }

```

I expect that `_image` of #Lint will not be executed because I overload its use. But When I run the command dagger do lint with the debug, I saw:

```log
1:56PM DEBUG actions.lint.markdown._image._pull | 
1:56PM DEBUG actions.lint.markdown._image._pull | #1 load metadata for docker.io/tmknom/markdownlint:0.31.1
1:56PM DEBUG actions.lint.markdown._image._pull | #1 sha256:feee7f006da16b0db8b62107f819956e1d36781bdd491fdc990afbb98947db75
1:56PM DEBUG actions.lint.markdown._image._pull | #1 DONE 0.6s
1:56PM DEBUG actions.lint.markdown._image._pull | 
1:56PM DEBUG actions.lint.markdown._image._pull | #4 Pull tmknom/markdownlint:0.31.1
1:56PM DEBUG actions.lint.markdown._image._pull | #4 sha256:09fe153992c62b62f14768de2b2a7cc3a0d967c56766728a5028a7dcd2dd204b
1:56PM DEBUG actions.lint.markdown._image._pull | #4 resolve docker.io/tmknom/markdownlint:0.31.1
1:56PM DEBUG actions.lint.markdown._image._pull | #4 resolve docker.io/tmknom/markdownlint:0.31.1 0.2s done
1:56PM DEBUG actions.lint.markdown._image._pull | #4 DONE 0.3s
// ...
1:56PM INFO  actions._image.markdownlint._pull | computing
1:56PM DEBUG actions._image.markdownlint._pull | dependency detected    dependency=client.commands.ecrPassword
1:56PM DEBUG actions._image.markdownlint._pull | add target credentials    target=00000.dkr.ecr.eu-west-3.amazonaws.com
1:56PM DEBUG actions._image.markdownlint._pull | 
1:56PM DEBUG actions._image.markdownlint._pull | #5 load metadata for 00000.dkr.ecr.eu-west-3.amazonaws.com/my/markdownlint::0.31.1-custom
1:56PM DEBUG actions._image.markdownlint._pull | #5 sha256:25bd9477404259feaf3666cf7a0753fb3cca4afeac1125f455df49c6b3d69c42
1:56PM DEBUG actions._image.markdownlint._pull | #5 DONE 0.1s
1:56PM INFO  actions._image.markdownlint._pull | completed    duration=200ms
```

That means, I pull 2. images instead of 1.

**Comment by guiyomh** [comment]
Ok, It's solved by separate Image definition and main action. Like it's describe in the documentation : https://docs.dagger.io/4dhu9/api-customizable-image#2-the-image-definition

example:
```yaml 
package markdown

import (
    "dagger.io/dagger"
    "universe.dagger.io/docker"
)

#Image: {
    repository: string | *"tmknom/markdownlint"
    tag:        string | *"0.31.1"
    // Registry authentication
    auth?: {
        username: string
        secret:   dagger.#Secret
    }

    docker.#Pull & {
        source: "\(repository):\(tag)"
        if auth != _|_ {
            "auth": auth
        }
    }
}

#Lint: {
    // source code
    source: dagger.#FS

    // Files to lint
    files: [...string]

    image: #Image

    docker.#Run & {
        input: *image.output | _
        mounts: "source": {
            dest:     "/src"
            contents: source
        }
        workdir: "/src"
        command: {
            name: "markdownlint"
            args: files
        }
    }
}
```

and in the plan, just I do:

```yaml
dagger.#Plan & {
  actions: {
    _source: core.#Source & {path: "."}
    _image:  markdown.#Image 

    "markdown": markdown.#Lint & {
      source: _source.output
      image:  _image
      files: ["README.md"]
    }
  }
}
```

or If I want to override the Image, I could do:

```yaml
dagger.#Plan & {
  actions: {
    _source: core.#Source & {path: "."}
    _image:  markdown.#Image & {
        repository: "\(_#DefaultAwsAccount).dkr.ecr.\(_#DefaultAwsRegion).amazonaws.com/public/tmknom/markdownlint"
         tag: "0.31.1"
        auth: {
            username: "AWS"
            secret:  client.commands.ecrPassword.stdout
        }
    }

    "markdown": markdown.#Lint & {
      source: _source.output
      image:  _image
      files: ["README.md"]
    }
  }
}
```
