### ISSUE TITLE
Auth parameters for pushing an image

### ISSUE THREAD

**Issue by munichbughunter** [dagger/dagger#3138]
### What are you trying to do?

I wanna push an image from a gitlab-ci to the gitlab container registry or to an artifactory. 
Before you can push images you must authenticate. 

First case -> GitLab Container Registry: 
In GitLab to use CI/CD authenticate, you can use the `CI_REGISTRY_USER` CI/CD variable. This variable has read-write access to the Container Registry and is valid for one job only. Its password is also automatically created and assigned to `CI_REGISTRY_PASSWORD`. 
When I run gitlab ci in a dind service we should be able to define that in the gql statement as parameter like that:

```
{
    host {
        workdir {
            read {
                dockerbuild(dockerfile: "../../Dockerfile") {
                    id
                    pushImage(
                        ref: "registry.gitlab.com/project:tag", user: $CI_REGISTRY_USER, pw: $CI_REGISTRY_PASSWORD 
                    )
                }
            }
        }
    }
}
```

Second case -> Artifactory:
```
{
    host {
        workdir {
            read {
                dockerbuild(dockerfile: "../../Dockerfile") {
                    id
                    pushImage(
                        ref: "registry.gitlab.com/project:tag", user: $ARTIFACT_USER, pw: $ARTIFACT_PASSWORD 
                    )
                }
            }
        }
    }
}
```

 

### Why is this important to you?

When I can't push any image to a container registry in an easy way then it makes no sense for me. 

### How are you currently working around this?

I will try a workaround like that to unblock myself. 
Creation of `~/.docker/config.json` and that content: 
```
{
    "auths": {
        "registry.example.com": {
            "auth": "Base 64 content"
        }
    }
}
```

Not cool, because then I have to push creds - in Base 64 - to the repo.

**Comment by aluzzardi** [comment]
@munichbughunter How do you currently push without dagger?

If you're able to `docker push`, then dagger should work out of the box -- it will re-use `dagger login` credentials automatically

**Comment by helderco** [comment]
In Gitlab this is what I do, doesn't it work for you?

```yaml
docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - xxxx
```
