### ISSUE TITLE
CI examples for each SDK

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3918]
Starting with:

- [x] Go SDK: GitHub Actions, CircleCI, GitLab, Jenkins
- [x] Python SDK: GitHub Actions, CircleCI, GitLab, Jenkins
- [x] Node.js SDK: GitHub Actions, CircleCI, GitLab, Jenkins using `.mjs` extension in examples
- [ ] Automated testing of CI snippets
- [ ] Tutorials

### What is the issue?

Need examples of how to run Dagger pipelines in the major CI providers with each SDK: Go, Python, Node.js (TS/JS)

CIs:
- GitHub Actions
- CircleCI
- Jenkins
- GitLab
- Azure DevOps - Azure Pipelines
- Tekton
- Travis
- AWS CodeBuild/Pipeline
- Jenkins X
- Drone / Woodpecker
- GCP CloudBuild
- Buildkite
- Argo
- Zuul
- Bitrise
- CodeFresh
- etc https://github.com/dagger/dagger/discussions/1677

For example:
to run a Python SDK pipeline in GitHub Actions, 
have simplified example like https://github.com/dagger/dagger/pull/3774/files#diff-e07285aaf3bcc46d779c86a6995427342bfe0d222b9416cf459d3ecdb7be6bc9
or
https://github.com/patrikbraborec/good-ci-cd/blob/main/.github/workflows/pipeline.yml

**Comment by marcindulak** [comment]
In addition to the CI examples, I would like to see docker examples on linux/macos/windows.

By this I mean the environment for the given sdk to be setup inside of a docker container. I've made also an example to explain what I mean https://github.com/marcindulak/dagger-dood-nodejs, it could be improved. I believe setting the environment with docker is needed in order to further approach a reproducibility between the local development environment of dagger, running on a developer machine and the environment in a CI provider. For simple examples this may not matter, but it will be useful for complex pipelines, and when reporting dagger bugs, like https://github.com/dagger/dagger/issues/3857.

Additionally I would like the examples of different CIs, and generally all dagger examples (especially the complex ones) to be tested https://github.com/dagger/dagger/issues/2552#issuecomment-1259973039.

**Comment by vikram-dagger** [comment]
I agree that we should have this. Ideally, each code sample should be embedded in a tutorial which explains how to use it and provides proper context. The structure as I see it is:
- code sample in a separate snippets file (so it gets tested and can be reused)
- tutorial listed in "guides" page which embeds the code sample and provides steps/walkthrough
- a "code samples" page under each SDK category in docs, which lists all available code samples

This allows a user to discover code samples in at least two ways ie. see all available samples via the "code samples" page (good for exploration) or find a specific sample and associated tutorial with detailed steps (good for specific problem solving).

**Comment by vikram-dagger** [comment]
Github: https://github.com/vikram-dagger/node/blob/main/.github/workflows/main.yml.keep
Gitlab: https://github.com/vikram-dagger/node/blob/main/.gitlab-ci.yml

**Comment by jpadams** [comment]
GitLab Node.js SDK:
```
.docker:
  image: docker:${DOCKER_VERSION}-git
  services:
    - docker:${DOCKER_VERSION}-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: '1'
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_CERT_PATH: '/certs/client'
    DOCKER_DRIVER: overlay2
    DOCKER_VERSION: '20.10.16'

.dagger:
  extends: [.docker]
  before_script:
    - apk add npm

build:
  extends: [.dagger]
  script:
    - npm run mydaggerscript
 ```

**Comment by jpadams** [comment]
```yaml
.docker:
  image: golang:1.19-alpine
  services:
    - docker:${DOCKER_VERSION}-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: '1'
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_CERT_PATH: '/certs/client'
    DOCKER_DRIVER: overlay2
    DOCKER_VERSION: '20.10.16'
.dagger:
  extends: [.docker]
  before_script:
    - apk add docker-cli
build:
  extends: [.dagger]
  script:
    - go run main.go
    ```
