### ISSUE TITLE
🐞 network issue with engine@v0.3.13 in k8s pod

### ISSUE THREAD

**Issue by morlay** [dagger/dagger#4652]
### What is the issue?

May cause by https://github.com/dagger/dagger/pull/4505

Here a new search in `/etc/resolv.conf` added before k8s searches

```conf
search dns.dagger
search gitlab.svc.cluster.local. svc.cluster.local. cluster.local. openstacklocal
options ndots:5
```

Then network because very slow to fetch anything.

### SDK version

Go SDK v0.4.6

### OS version

Unbuntu

**Comment by morlay** [comment]
Sorry. missing to add this new configuration to `/etc/dagger/engine.toml`

```toml
[worker.oci]
networkMode = "cni"
cniConfigPath = "/etc/buildkit/cni.conflist"

[worker.containerd]
networkMode = "cni"
cniConfigPath = "/etc/buildkit/cni.conflist"
```

Have to use custom engine toml with `registry` mirror settings

**Comment by morlay** [comment]
However, some address is not touchable

```
Failed to fetch http://repo.huaweicloud.com/debian-security/dists/bullseye-security/InRelease  Connection failed [IP: 123.125.16.223 80]
```

**Comment by Alvise88** [comment]
I have the same issue, dagger version on K8s cannot resolve DNS names correctly.

**Comment by vito** [comment]
Looking into this now!

It might be a lot to ask, but if anyone can whittle this down to minimal repro I'd be greatly appreciative since network issues tend to be troublesome to debug.

**Comment by vito** [comment]
Merged a couple of changes: one to make services opt-in (#4657) and another to tweak the DNS setup to resolve some theoretical issues (#4658).

I'm unable to hit any issues in a local `kind` cluster, but I've built and pushed an image with those changes if anyone wants to try it:

```
vito/dagger-engine:dev
vito/dagger-engine@sha256:ced5b152ac59d521329e8a5c6e7eae74a15c2c4d9836a38b40c85a5313b6c6f7
```

Note that since it's opt-in you'll need to set the `_EXPERIMENTAL_DAGGER_SERVICES_DNS` env var. Here's the pod I used to test:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dagger
spec:
  containers:
  - name: dagger
    # image: registry.dagger.io/engine:v0.3.13
    image: vito/dagger-engine@sha256:ced5b152ac59d521329e8a5c6e7eae74a15c2c4d9836a38b40c85a5313b6c6f7
    securityContext:
      privileged: true
    env:
    - name: _EXPERIMENTAL_DAGGER_SERVICES_DNS
      value: "1"
```

If @Alvise88 or @morlay or anyone else is brave enough to try out my image and see if it fixes this issue I'd greatly appreciate it. :)
