### ISSUE TITLE
🐞 Degraded performance with socket connection on Kubernetes

### ISSUE THREAD

**Issue by schlapzz** [dagger/dagger#5625]
### What is the issue?

I currently try to implement the Dagger engine in our OpenShift cluster to get them work together with our self hosted GitLab runners. So far everything is working, but I experienced some performance problems with my setup.

### Local to local engine

First run local without initialized cache
```
• Engine: 2066df0daca0 (version v0.8.2)
• Duration: 40.388s
```

Second run local with  initialized cache
```
• Engine: 2066df0daca0 (version v0.8.2)
• Duration: 2.903s
```

### Local to remote Kubernetes engine

Set dagger runner host: `export _EXPERIMENTAL_DAGGER_RUNNER_HOST=kube-pod://dagger-engine-25dwl`

First run local without initialized cache
```
• Engine: dagger-engine-25dwl (version v0.8.2)
• Duration: 10.245s
```

Second run local with  initialized cache
```
• Engine: dagger-engine-25dwl (version v0.8.2)
• Duration: 2.9s
```

### Pod to Kubernetes engine with socket

Set dagger runner host in builder pod: `export _EXPERIMENTAL_DAGGER_RUNNER_HOST=unix:///var/run/dagger/buildkitd.sock`

First run local with initialized cache (initialized by the run before)
```
• Engine: dagger-engine-25dwl (version v0.8.2)
• Duration: 2m4.501s
```

⚠️ The first execution of the pipeline took about 2 minutes! For the first 90s there is no log output and I assume Dagger is trying to connect to the engine and starting a new session. 

```
root@builder:/src/dagger-pipeline-test# dagger run go run ci/main.go
█ [124.5s] go run ci/main.go
┃ ttl.sh/soaisbvj:5m@sha256:4066098da92f5dd859fd244ad4804f54acf5c5ef2763a21b985b0e976739dd75
┣─╮
│ ▽ host.directory .
│ █ [0.13s] upload .
│ ┣ [0.03s] transferring eyJvd25lcl9jbGllbnRfaWQiOiJ4dWtpOGpyejdhdHMwMzZiZ3pxdm41Nm4wIiwicGF0aCI6Ii4iLCJpbmNsdWRlX3BhdHRlcm5zIjpudWxsLCJleGNsdWRlX3BhdHRlcm5zIjpbImNpLyIsImJ1aWxkLyJdLCJmb2xsb3dfcGF0aHMiOm51bGwsInJlYWRfc2luZ2xlX2ZpbGVfb25seSI6ZmFsc2UsIm1heF9maWxlX3NpemUiOjB9:
│ █ [0.14s] upload .
│ ┣ [0.01s] transferring eyJvd25lcl9jbGllbnRfaWQiOiJ4dWtpOGpyejdhdHMwMzZiZ3pxdm41Nm4wIiwicGF0aCI6Ii4iLCJpbmNsdWRlX3BhdHRlcm5zIjpbImdvLm1vZCIsImdvLnN1bSJdLCJleGNsdWRlX3BhdHRlcm5zIjpudWxsLCJmb2xsb3dfcGF0aHMiOm51bGwsInJlYWRfc2luZ2xlX2ZpbGVfb25seSI6ZmFsc2UsIm1heF9maWxlX3NpemUiOjB9:
│ █ [0.09s] copy . (exclude ci/, build/)
│ ┣─╮ copy . (exclude ci/, build/)
│ █ │ CACHED copy . (include go.mod, go.sum)
│ ┣─┼─╮ copy . (include go.mod, go.sum)
│ ┻ │ │
┣─╮ │ │
│ ▽ │ │ from golang:1.20
│ █ │ │ [0.89s] resolve image config for docker.io/library/golang:1.20
│ █ │ │ [0.04s] pull docker.io/library/golang:1.20
│ ┣ │ │ [0.04s] resolve docker.io/library/golang:1.20@sha256:37c7d8580e0616e96914a67291b9693fe038ab677eb9b5deb81e541b2322f20f
│ ┣─┼─┼─╮ pull docker.io/library/golang:1.20
│ ┻ │ │ │
█◀──╯ │ │ [0.07s] copy / /src
█◀────╯ │ CACHED copy / /src
█◀──────╯ CACHED merge (pull docker.io/library/golang:1.20, copy / /src)
█ CACHED exec go mod download
█ [1.08s] merge (exec go mod download, copy / /src)
┣ [1.08s] merging
█ [0.88s] exec go build -o myapp1
┣─╮
│ ▽ from alpine
│ █ [0.45s] resolve image config for docker.io/library/alpine:latest
│ █ [0.04s] pull docker.io/library/alpine:latest
│ ┣ [0.03s] resolve docker.io/library/alpine@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a
│ ┣─╮ pull docker.io/library/alpine:latest
│ ┻ │
█   │ CACHED copy /src/myapp1 /bin/myapp
█◀──╯ CACHED merge (pull docker.io/library/alpine:latest, copy /src/myapp1 /bin/myapp)
┻
• Engine: dagger-engine-25dwl (version v0.8.2)
• Duration: 2m4.501s

```

If I re-run the pipeline again in the same pod, the log output starts immediately and the pipeline finish under 5 seconds. 
```
• Engine: dagger-engine-25dwl (version v0.8.2)
• Duration: 4.197s
```

I'm not quite sure if it is a Dagger or Kubernetes/OpenShift related problem. Didn't have the chance yet to test it on another cluster setup. 

### Steps to reproduce

<details>
  <summary>engine-daemonset.yaml</summary>

```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: dagger-engine
  namespace: pitc-dagger-test
  labels:
    k8s-app: dagger-engine
spec:
  selector:
    matchLabels:
      name: dagger-engine
  template:
    metadata:
      labels:
        name: dagger-engine
    spec:
      volumes:
        - name: shared-bin
          emptyDir: {}
        - name: varlibdagger
          hostPath:
            path: /var/lib/dagger
            type: ''
        - name: varrundagger
          hostPath:
            path: /var/run/dagger
            type: ''
      initContainers:
        - name: download-bin
          image: 'ghcr.io/dagger/engine:v0.8.2'
          command:
            - sh
            - '-c'
            - >-
              wget
              https://github.com/moby/buildkit/releases/download/v0.11.6/buildkit-v0.11.6.linux-amd64.tar.gz
              -O /shared-bin/buildkit.tar.gz && tar -xvzf
              /shared-bin/buildkit.tar.gz --strip-components 1 bin/buildctl -C
              /shared-bin
          resources: {}
          volumeMounts:
            - name: shared-bin
              mountPath: /shared-bin
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - resources:
            limits:
              cpu: 1500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /shared-bin/buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: dagger-engine
          securityContext:
            capabilities:
              add:
                - ALL
            privileged: true
          imagePullPolicy: Always
          volumeMounts:
            - name: varlibdagger
              mountPath: /var/lib/dagger
            - name: varrundagger
              mountPath: /var/run/buildkit
            - name: shared-bin
              mountPath: /shared-bin
          terminationMessagePolicy: File
          image: 'ghcr.io/dagger/engine:v0.8.2'
          args:
            - '--oci-max-parallelism'
            - num-cpu
      restartPolicy: Always
      terminationGracePeriodSeconds: 300
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 0
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
```
</details>

<details>
  <summary>pod.yaml</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: builder
  namespace: pitc-dagger-test
spec:
  containers:
  - image: golang:1.20
    imagePullPolicy: Always
    name: helper
    tty: true
    env:
    - name: _EXPERIMENTAL_DAGGER_RUNNER_HOST
      value: unix:///var/run/dagger/buildkitd.sock
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      capabilities:
        drop:
        - NET_RAW
      privileged: true
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/dagger
      name: dagger
  restartPolicy: Never
  securityContext:
    fsGroup: 1001
    runAsGroup: 1001
    runAsNonRoot: false
    runAsUser: 0
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 0
  volumes:
  - hostPath:
      path: /var/run/dagger
      type: ""
    name: dagger
```
</details>

Steps to reproduce:
1. Create Dagger engine deamon set `kubectl apply -f engine-deamonset.yaml`
2. Create build pod (in reality this is spanwed by our Gitlab Runners) `kubectl apply -f pod.yaml`
3. Open shell into container `kubectl exec --stdin --tty builder -- /bin/bash`
4. Install Dagger and clone git project `git clone https://github.com/schlapzz/dagger-pipeline-test.git`
5. Start pipeline `dagger run go run ci/main.go`

### SDK version

Go SDK 0.8.2

### OS version

Openshift 4.12 / Kubernetes 1.25
