### ISSUE TITLE
No information on caching for CI environments

### ISSUE THREAD

**Issue by noah-troncoso** [dagger/dagger#6911]
### What is the issue?

I can't find any information in the most recent documentation on how to persist the cache created by Dagger between pipelines in a CI environment (Github Actions for my use case). This used to be available, [such as in version 0.2](https://archive.docs.dagger.io/0.2/1237/persistent-cache-with-dagger/#persistent-cache-in-github-actions), but now it seems everything related is pushing me towards Dagger Cloud.

So how can I persist cache in a CI environment?

**Comment by noah-troncoso** [comment]
Thinking more on this, I really think I just need to know where the cache is stored so I can use Github Action's built in caching mechanisms to restore it for each run

**Comment by noah-troncoso** [comment]
I found a post on Discord about this here: https://discord.com/channels/707636530424053791/1165204052154535956

So, clearly the reason it's not talked about in the docs is because Dagger requires you to use Dagger Cloud for caching. So it's completely handicapped in production without paying money.

**Comment by purpleclay** [comment]
Would this approach not work: https://docs.dagger.io/integrations/104820/kubernetes ? Granted, it isn't a persistent cache like Dagger Cloud, but you could have a Dagger Engine that is always on in the cluster

**Comment by noah-troncoso** [comment]
I don't think it makes a lot of sense to stand up a separate permanent dagger engine just to support caching, which is one of Dagger's biggest selling points. [It seems people get their own cache working by simply backing up and restoring the `/var/lib/dagger` directly](https://discord.com/channels/707636530424053791/1134307062009053294). All the while, the Dagger team claims that caching in Github Actions was too complicated to continue supporting it. From that same discord thread, I found that Dagger does have an experimental cache config in the form of `_EXPERIMENTAL_DAGGER_CACHE_CONFIG`, but I can't for the life of me get it to work. There's not a shred of documentation for this either.

Re-iterating on the fact that Dagger really plays up caching in their marketing, it's pretty disappointing that they offer very little options in that regard. I quite literally just want the same caching in my pipeline that I get on my local machine. I shouldn't have to spin up a server just to get that workign.

**Comment by Depado** [comment]
Looks like it's currently being worked on: https://github.com/dagger/dagger/issues/8004

**Comment by Xiol** [comment]
None of the Discord links in this thread work anymore. Context has been lost.

**Comment by nstandif** [comment]
Got `_EXPERIMENTAL_DAGGER_CACHE_CONFIG=type=gha` working on standard GHA runners. GHA no longer auto-exposes `ACTIONS_CACHE_URL` and `ACTIONS_RUNTIME_TOKEN`, so this is what is likely causing issues. Using [`crazy-max/ghaction-github-runtime@v3`](https://github.com/crazy-max/ghaction-github-runtime) is a workaround, along with passing `url=` and `token=` in the config. Got `CACHED` labels, but that's all I have as far as evidence.

My config:

```yaml
- uses: crazy-max/ghaction-github-runtime@v3

- name: Build cache config
  id: cache-config
  run: |
    URL="${ACTIONS_RESULTS_URL:-$ACTIONS_CACHE_URL}"
    echo "::add-mask::${ACTIONS_RUNTIME_TOKEN}"
    echo "config=type=gha,mode=max,scope=dagger-${GITHUB_REF_NAME},url=${URL},token=${ACTIONS_RUNTIME_TOKEN}" >> "$GITHUB_OUTPUT"

- name: Run Dagger
  env:
    _EXPERIMENTAL_DAGGER_CACHE_CONFIG: ${{ steps.cache-config.outputs.config }}
  uses: dagger/dagger-for-github@v7
  with:
    version: "0.20.1"
    verb: call
    args: your-function --source=.
```
