### ISSUE TITLE
Document how to configure local cache size

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#7022]
There is a way to configure the size of the local buildkit cache, but it's not in the docs.

**Comment by pck** [comment]
Something like this works for me:

```toml
# To customize the size of the cache, manually start the Dagger Engine with a custom engine.toml:
#
#     docker run -d --rm --name dagger-engine --privileged --volume dagger-engine:/var/lib/dagger
#         --volume ./engine.toml:/etc/dagger/engine.toml registry.dagger.io/engine:v0.10.3
#     export _EXPERIMENTAL_DAGGER_RUNNER_HOST=docker-container://dagger-engine
#

debug = true
insecure-entitlements = ["security.insecure"]

[worker.oci]
gc = true
gckeepstorage = "45GB"
# max-parallelism = 10
[[worker.oci.gcpolicy]]
keepBytes = "4GB"
keepDuration = "240h"
filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
[[worker.oci.gcpolicy]]
keepBytes = "30GB"
keepDuration = "720h"
[[worker.oci.gcpolicy]]
keepBytes = "40GB"
[[worker.oci.gcpolicy]]
all = true
keepBytes = "45GB"
```

This mimics the structure of the default GCPolicy settings with different values. Probably this should be simplified or explained.

Maybe the example "docker run" command in https://docs.dagger.io/manuals/administrator/272381/custom-registry should also include `--volume dagger-engine:/var/lib/dagger`.
