### ISSUE TITLE
Take environment variable as input

### ISSUE THREAD

**Issue by TomChv** [dagger/dagger#873]
## Request

During a user interview with @grouville, the user told us that it would be cool to give environment variable as input.

I told him to just send it as a string (e.g: `dagger input text key "$MY_ENV_VAR"`) but it wasn't his objective, we wanted to directly use the environment, not a static value.

I think that could be a good idea to add this feature to dagger

## What I would like to see

```
// Cue file
import (
    "alpha.dagger.io/dagger"
)

key: dagger.#Input &  { string }
```

```bash
dagger input env key MY_ENV_VAR
```

We could store this in `values.yaml` like that

```yaml
plan:
    package: xxxx
inputs:
    key:
        env: MY_ENV_VAR
sops:
     ....
```

Then in execution, we simply retrieve the value from environment :rocket:

/cc @aluzzardi What is your opinion about that feature ?
