### ISSUE TITLE
docs: Using git credential helpers in CI examples

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#8989]
Some users have been encountering issues when trying out out Git credential helpers in CI

I am moving the conversation to its own issue @pspurlock, and cleaning up the other (everything was screenshotted)

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/f4f26f32-6fd8-4aa5-b54f-9f57ce897ac6">
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/201f725c-8bec-44f8-8326-6c59bce49187">
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/0cf1df5d-fef7-4102-92fb-3a3452b70816">
<img width="1016" alt="image" src="https://github.com/user-attachments/assets/e809f04f-0cee-4e10-830e-f7d90b066218">

After discussing with @nipuna-perera, they do manage to make it work ; It seems to be a configuration issue / patterns to use, which shall become a standard.

Next step on my end: 
- [ ] Working repro for GitHub / GitLab / BitBucket

**Comment by grouville** [comment]
hey @pspurlock

I have a working implementation:

```yaml
image: docker:latest

services:
  - name: docker:${DOCKER_VERSION}-dind
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: '1'
  DOCKER_TLS_CERTDIR: '/certs'
  DOCKER_CERT_PATH: '/certs/client'
  DOCKER_DRIVER: overlay2
  DOCKER_VERSION: '24.0.6'
  GIT_USERNAME: "grouville"
  GIT_TOKEN: "${PAT}"

stages:
  - build

dagger_job:
  stage: build
  before_script:
    # Install required packages
    - apk add --no-cache git curl

    # Install Dagger
    - curl -L https://dl.dagger.io/dagger/install.sh | sh
    - mv bin/dagger /usr/local/bin
    - chmod +x /usr/local/bin/dagger

    # Configure Git credentials with improved script
    - |
      cat > /tmp/git-credential-helper.sh << 'EOF'
      #!/bin/sh
      case "$1" in
          get)
              if [ -n "$GIT_USERNAME" ] && [ -n "$GIT_TOKEN" ]; then
                  echo "username=$GIT_USERNAME"
                  echo "password=$GIT_TOKEN"
              fi
              ;;
          store)
              # Don't store credentials
              ;;
          erase)
              # Don't need to erase credentials
              ;;
      esac
      exit 0
      EOF
    - chmod +x /tmp/git-credential-helper.sh

    # Configure git with the helper and additional settings
    - git config --global credential."https://github.com".helper "/tmp/git-credential-helper.sh"
    - git config --global credential."https://github.com".useHttpPath true

  script:
    # Run Dagger commands
    - dagger -m github.com/grouville/daggerverse-private/zip functions

    # Graceful shutdown for cache
    - |
      if docker ps --filter name="dagger-engine-*" -q; then
        docker stop -t 300 $(docker ps --filter name="dagger-engine-*" -q)
      fi

```

Just add the PAT secret as an env var and replace the dagger command as well as the username

**Comment by vikram-dagger** [comment]
> cc @vikram-dagger, where shall i document those examples ?

https://docs.dagger.io/integrations/gitlab would work - thanks for creating this example :)

**Comment by pspurlock** [comment]
@grouville Thanks for doing this. I can't try out your example fully because dind requires privileged mode for the runner which we don't allow. However, I did try to mimic it as much as possible and still get the same access denied error.

For context, we have a gitlab runner deployed alongside a dagger engine/deamon in a cluster. When we run a CI Job, we then use `_EXPERIMENTAL_DAGGER_RUNNER_HOST` so that the CI Job will connect and use the daemon running in the cluster. So when `dagger -m mymodule call ...` is ran, which git credential context is being used here? The one running in the CI Job that is running the dagger call command, or the host we are connecting to?

I have tried to add credentials in both places and neither have worked, but it would help to clarify. I know it isn't a credential issue because I can run the same credential helper commands and then `git clone` successfully before the dagger command fails.

Thanks a ton for your quick response/feedback on this.

**Comment by grouville** [comment]
Mmmh, weird 😢 i'd be happy to sync with you to debug that live

Normally, the source of truth is always the CLI, so the one running in the CI Job that is running the dagger call command. I'll try with the `_EXPERIMENTAL_DAGGER_RUNNER_HOST`, if there's a bug, but I don't think so.

**Comment by grouville** [comment]
> I have tried to add credentials in both places and neither have worked, but it would help to clarify. I know it isn't a credential issue because I can run the same credential helper commands and then git clone successfully before the dagger command fails.

If you make the same behavior as I did above, basically setting your own credential helper, if you add a step that actually prints it: 

```yaml
- script:
    # this should print user and pat -- please ensure that 
    - /tmp/git-credential-helper.sh get 
    # Run Dagger command
    - dagger -m github.com/grouville/daggerverse-private/zip functions
```

**Comment by grouville** [comment]
> @grouville Thanks for doing this. I can't try out your example fully because dind requires privileged mode for the runner which we don't allow. However, I did try to mimic it as much as possible and still get the same access denied error.
> 
> For context, we have a gitlab runner deployed alongside a dagger engine/deamon in a cluster. When we run a CI Job, we then use `_EXPERIMENTAL_DAGGER_RUNNER_HOST` so that the CI Job will connect and use the daemon running in the cluster. So when `dagger -m mymodule call ...` is ran, which git credential context is being used here? The one running in the CI Job that is running the dagger call command, or the host we are connecting to?
> 
> I have tried to add credentials in both places and neither have worked, but it would help to clarify. I know it isn't a credential issue because I can run the same credential helper commands and then `git clone` successfully before the dagger command fails.
> 
> Thanks a ton for your quick response/feedback on this.

Ok, could you please share what your gitconfig looks like ? Even privately, it would help. Are you using a proxy ?

**Comment by nipuna-perera** [comment]
FWIW, This is what we do. I've tested this to work on our Jenkins runners.

```Groovy
sh("git config --global credential.https://github.com.helper \'!f() { sleep 1; echo \"username=\${${username}}\";\n"+
      "echo \"password=\${${password}}\"; }; f\'")
```

It's basically doing the helper function inline.

**Comment by pspurlock** [comment]
Ok I got it! It wasn't a git-config issue, it WAS a token issue, I just don't know why:

```yaml
dagger test:
  extends: .dagger
  stage: test
  variables:
    GIT_USERNAME: gitlab-ci-token
  script:
    - |
      cat > /tmp/git-credential-helper.sh << 'EOF'
      #!/bin/sh
      case "$1" in
          get)
              if [ -n "$GIT_USERNAME" ]; then
                  echo "protocol=https"
                  echo "username=$GIT_USERNAME"
                  echo "password=$CI_JOB_TOKEN"
              fi
              ;;
          store)
              # Don't store credentials
              ;;
          erase)
              # Don't need to erase credentials
              ;;
      esac
      exit 0
      EOF
    - chmod +x /tmp/git-credential-helper.sh

    - git clone https://myproject.com.git || true
    - git config --system credential."https://myproject.com".helper "/tmp/git-credential-helper.sh"
    - echo -e "host=myproject.com\nprotocol=https\n" | git credential fill
    - git clone https://myproject.com.git
    - dagger -v -m https://myproject.com/ruff call lint -h
```

The git clones before the dagger calls are my sanity checks -- first clone before the config (to make sure it fails as it should), then one after to make sure it passes after my git config is changed. 

Scenario #1 - Use $CI_JOB_TOKEN

1st git clone fails, 2nd git clone works. That's what I'd expect. Dagger, however fails.

Scenario #2 - Use $TEST_DAGGER_TOKEN -- A var I created with a PAT from our private dagger module repo.

Same as above, except this time Dagger also works successfully! So the only change being made is the token, but the token not working for dagger DOES work when doing a git clone.

If I had to guess, maybe Dagger is making a call that CI_JOB_TOKEN doesn't have access to? It is limited in scope so it does NOT have full API access. [reference](https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html)

Thanks again for sticking with me, you guys are awesome.
