### ISSUE TITLE
🖐️ Question - Running Dagger in my GitLab CI

### ISSUE THREAD

**Issue by cavo789** [dagger/dagger#9074]
### What happened? What did you expect to happen?

Hi all

I'm trying to run my Dagger pipeline in a GitLab CI and I get an error while connecting to the Dagger engine.

Here my `.gitlab-ci.yml` file (almost the same than [https://docs.dagger.io/integrations/gitlab/#examples](https://docs.dagger.io/integrations/gitlab/#examples))

```yaml
.docker:
  image: docker:latest
  services:
    - docker:${DOCKER_VERSION}-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: false
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_CERT_PATH: '/certs/client'
    DOCKER_DRIVER: overlay2
    DOCKER_VERSION: '27.3.1'
.dagger:
  extends: [.docker]
  before_script:
    - apk add curl
    - curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin sh
lint:
  extends: [.dagger]
  script:
    - docker --version
    - docker info
    - dagger call --source src --config .config lint
```

And here the error

![391134744-458cf054-249b-4578-b154-583be91e3daa](https://github.com/user-attachments/assets/86dc5184-88a8-4815-a412-ad3762be89df)

The command `docker --version` returns `Docker version 27.3.1, build ce12230`  and `docker info` is well giving me all the informations (so DIND is working I think).

Can someone help please?

Thanks!!!

**Comment by jedevc** [comment]
Hm, interesting :thinking: The error you're seeing is generally because the client cannot connect to the dagger engine - but it looks like the container has started.

Can you share the results of `docker ps -a` as well? I wonder if the dagger container is actually running. Also, could you share the results of `docker logs dagger-engine-v0.14.0`, it's possible the container has some error that is rejecting client connections.

**Comment by cavo789** [comment]
Thanks for your answer and time.

I'll be back at the office Thursday, will answer to your questions then. Thanks.

**Comment by cavo789** [comment]
Seems my gitlab_user can't access to these commands:

![2024-12-05_10h33_57](https://github.com/user-attachments/assets/0905353e-bb7a-443a-8ef4-fb89035d140c)

while for these ones yes

![2024-12-05_10h34_42](https://github.com/user-attachments/assets/a6a8eacf-cac7-4a06-8212-ab2161c8d913)

I'll continue the investigation.  Thanks for the tip.

**Comment by grouville** [comment]
> Is this possible it's something to do (apk update && apk upgrade iptables) in your Docker image (v0.14.0) ?

Hello, I think it is a config conflict on your runner ; could you please elaborate if you are indeed running the runner as `privileged` ? This is mandatory for `dind`: https://gitlab.com/gitlab-org/gitlab-runner/-/blob/main/docs/executors/kubernetes/index.md#L1833-1835

Here is a list of small things to try to keep isolating the root cause:

- Add a step in the CI job before running Dagger to test iptables:
```
yaml
script:
  - docker run --rm --privileged alpine:latest sh -c 'apk add iptables && iptables -t nat -L'
```

If this fails, it confirms an iptables / NAT issue, probably coming from the privilege issue above

- Verify that the GitLab runner is privileged:
Check the config.toml on the runner’s host and ensure privileged = true under [runners.docker].

**Comment by cavo789** [comment]
**Many, many thanks for your input and time.** I would really be happy to try Dagger on my CI and, if possible, replace our existing CIs.

I've added the line suggested line in my `.gitlab-ci.yml` file and **it's works** as illustrated below.

![2024-12-09_08h59_45](https://github.com/user-attachments/assets/6ed2e4db-2f01-403a-86f6-048198d01fd2)

Here is my entire yaml file:

```yaml
.docker:
  image: docker:latest
  services:
    - docker:${DOCKER_VERSION}-dind
  variables:    
    DOCKER_HOST: unix:///var/run/docker.sock 
.dagger:
  extends: [.docker]
  before_script:    
    - apk add curl
    - curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin sh
lint:
  extends: [.dagger]
  script:
    - printf "\e[1;34m%s\e[m\n" "Update iptables"
    - docker run --rm --privileged alpine:latest sh -c 'apk add iptables && iptables -t nat -L'
    - printf "\e[1;34m%s\e[m\n" "docker container list --all | sort"
    - docker container list --all | sort
    - printf "\e[1;34m%s\e[m\n" "docker logs dagger-engine-v0.14.0"
    - dagger call --source src --config .config lint
```

When it's time to run `dagger call --source src --config .config lint` it takes a while then I got an error

![2024-12-09_09h36_47](https://github.com/user-attachments/assets/af37a60b-4638-4599-918c-ee8d822e241a)

I've made a SSH connection on my Gitlab runner server and my `/etc/gitlab-runner/config.toml` have well the priviledged setting on true:

```toml

[[runners]]
  [runners.docker]
    privileged = true
```

Here the last lines on my log:


```bash
>  docker logs dagger-engine-v0.14.0 -n 30

# expect more open files due to per-client SQLite databases
# many systems default to 1024 which is far too low
ulimit -n 1048576 || echo "cannot increase open FDs with ulimit, ignoring"

exec /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml "$@"
dnsmasq[28]: started, version 2.90 cachesize 150
dnsmasq[28]: compile time options: IPv6 GNU-getopt no-DBus no-UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-nftset auth no-cryptohash no-DNSSEC loop-detect inotify dumpfile
dnsmasq[28]: warning: interface dagger0 does not currently exist
dnsmasq[28]: using only locally-known addresses for dagger.local
dnsmasq[28]: reading /etc/dnsmasq-resolv.conf
dnsmasq[28]: using nameserver 10.100.0.5#53
dnsmasq[28]: using nameserver 10.100.0.7#53
dnsmasq[28]: using only locally-known addresses for dagger.local
time="2024-12-09T08:51:04Z" level=info msg="detected mtu 1500 via interface eth0"
dnsmasq[28]: read /etc/hosts - 18 names
dnsmasq[28]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
time="2024-12-09T08:51:04Z" level=debug msg="engine name: 6ac033d9f746"
time="2024-12-09T08:51:04Z" level=debug msg="creating engine GRPC server"
time="2024-12-09T08:51:04Z" level=debug msg="creating engine lockfile"
time="2024-12-09T08:51:04Z" level=debug msg="creating engine server"
time="2024-12-09T08:51:04Z" level=info msg="auto snapshotter: using overlayfs"
time="2024-12-09T08:51:04Z" level=warning msg="failed to release network namespace \"ik9xzfg02fpq1wuuwp7nu8rkr\" left over from previous run: plugin type=\"loopback\" failed (delete): unknown FS magic on \"/var/lib/dagger/net/cni/ik9xzfg02fpq1wuuwp7nu8rkr\": 58465342"
buildkitd: failed to create engine: failed to create network providers: CNI setup error: plugin type="bridge" failed (add): failed to list chains: running [/usr/sbin/iptables -t nat -S --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory
iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```
