### ISSUE TITLE
🐞 Potential regression in dagger.ContainerWithFileOpts permissions

### ISSUE THREAD

**Issue by liamjones-pw** [dagger/dagger#9250]
### What is the issue?

Initially reported [in Discord](https://discord.com/channels/707636530424053791/1117139064274034809/1318921838570504295), Dagger 0.15.1 running on GitHub Actions doesn't appear to respect `ContainerWithFileOpts` permissions as it did previously in 0.14. 

The permissions are applied as defined in the dagger code in these cases:

- Local 
  - 0.14.x ✅ 
  - 0.15.x ✅ 
- GitHub-hosted Runner
  - 0.14.x ✅ 
  - 0.15.x 🚫 

I expected the permissions set in Dagger to be applied.

### Dagger version

dagger v0.15.1

### Steps to reproduce

- Build a container using the Dagger GHA on a GitHub-hosted Runner, copying a file into the container using `dagger.ContainerWithFileOpts{Permissions: 0500}`.
- Check the permissions of the file inside the built container. 

Abbreviated code below.

```go
	dag.Container(dagger.ContainerOpts{Platform: platform}).
		// ...
		WithFile("entrypoint.sh", src.File("entrypoint.sh"), dagger.ContainerWithFileOpts{Permissions: 0500}).
```

Issue was discovered when workloads deployed using the built image failed to start because the entrypoint wasn't executable, as it carried the of 0644 from the runner.

### Log output

I noticed log output in the GHA that I wasn't seeing for 0.14.x, such as the below.

```
3   : │ │ starting engine DONE [8.5s]
9   : │ │ connecting to engine
10  : │ │ │ moby.buildkit.v1.Control/Info
10  : │ │ │ moby.buildkit.v1.Control/Info ERROR [0.1s]
10  : │ │ │ ! connection error: desc = "error reading server preface: command [docker exec -i dagger-engine-v0.15.1 buildctl dial-stdio] has exited with exit status 1, make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=Error: dial unix /run/buildkit/buildkitd.sock: connect: no such file or directory\nUsage:\n  dial-stdio [flags]\n\nFlags:\n      --addr string   The address serving the grpc api (default \"unix:///run/buildkit/buildkitd.sock\")\n  -h, --help          help for dial-stdio\n      --timeout int   The timeout in seconds for connecting to the grpc api (default 5)\n\n"
```

I haven't tested with a simplified version where I can easily share the full log output, if you'd like me to do so before further investigation, let me know.

**Comment by jedevc** [comment]
Investigating this now, will let you know if I need more info! Sorry for the delay!

---

One note... the dialing issue you see in the log output is likely caused  by the engine startup taking longer than it used to. I *suspect* that this may be fixed by https://github.com/dagger/dagger/pull/9430 (which is where I was seeing such a slow-down). Regardless, I think this is *probably* unrelated to the permissions issue.

Were you using a shared `/var/lib/dagger` between different dagger jobs?

**Comment by jedevc** [comment]
Okay, I've tried to reproduce what you're seeing, and kind of struggling.

So, I've setup a test repo https://github.com/jedevc/repro-dagger-9250 - here's the go code:

```go
package main

import (
	"dagger/example/internal/dagger"
)

type Example struct{}

func (m *Example) Test(mydir *dagger.Directory) *dagger.Container {
	return dag.Container().From("alpine").
		WithFile("entrypoint.sh", mydir.File("entrypoint.sh"), dagger.ContainerWithFileOpts{Permissions: 0500})
}
```

and the github action:

```yaml
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: "Create file"
        run: |
          mkdir /tmp/workplace
          cd /tmp/workplace

          echo -e "#!/bin/sh\necho hello world" > entrypoint.sh
          ls -lh entrypoint.sh

      - name: "Test"
        id: test
        uses: dagger/dagger-for-github@v6
        with:
          version: v0.15.2
          args: test --mydir=/tmp/workplace with-exec --args "ls,-lh,entrypoint.sh" stdout
```

The output looks like this: https://github.com/jedevc/repro-dagger-9250/actions/runs/12990803809/job/36226854497

```
-rw-r--r-- 1 runner docker 27 Jan 27 14:08 entrypoint.sh
...
-r-x------    2 root     root          27 Jan 27 14:08 entrypoint.sh
```

Which is what I'd expect - but you're saying you're seeing something different.

Am I missing something from your instructions? Any chance you could help with a simplified example, so we can try and reproduce it? Thanks! :tada:
