### ISSUE TITLE
Running the Engine in kata-containers fails with `failed to create hash for : operation not supported`

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#9319]
<details>
<summary>Given the following Talos v1.9.1 cluster:</summary>

```yaml
kind: Cluster
name: dagger-ci-2025-01-02
talos:
  version: v1.9.1
kubernetes:
  version: v1.32.0
patches:
  # Single-node cluster FTW! 💪
  - name: allow-scheduling-on-controlplanes
    file: ../patches/allow-scheduling-on-controlplanes.yaml
  # https://www.talos.dev/v1.9/talos-guides/network/kubespan
  - name: kubespan
    file: ../patches/kubespan.yaml
  # https://github.com/siderolabs/omni-feedback/issues/41
  # https://sysctl-explorer.net/vm/oom_kill_allocating_task/
  - name: oom-kill-allocating-task
    file: ../patches/oom-kill-allocating-task.yaml
  # All the following are required for kube-prometheus-stack to access these metrics
  - name: etcd-metrics
    file: ../patches/etcd-metrics.yaml
  - name: kube-proxy-metrics
    file: ../patches/kube-proxy-metrics.yaml
  - name: kube-scheduler-metrics
    file: ../patches/kube-scheduler-metrics.yaml
  - name: kube-controller-manager-metrics
    file: ../patches/kube-controller-manager-metrics.yaml
  - name: sidecar-containers
    file: ../patches/cluster-sidecar-containers.yaml
  # Requires kubelet patch, otherwise it would be GitOps'd
  - name: metrics-server
    file: ../patches/metrics-server.yaml
  - name: user-namespaces
    file: ../patches/cluster-user-namespaces.yaml
# https://pxe.factory.talos.dev/
systemExtensions:
  - siderolabs/spin
  - siderolabs/kata-containers
---
kind: ControlPlane
machines:
  - 669aa7b6-bfde-11d3-01a8-9c6b004ef365
---
kind: Workers
machines: []
---
kind: Machine
name: 669aa7b6-bfde-11d3-01a8-9c6b004ef365
install:
  disk: /dev/nvme0n1
patches:
  - name: network
    file: ../patches/d24-10-22-network.yaml
  - name: machine-sidecar-containers
    file: ../patches/machine-sidecar-containers.yaml
  - name: machine-user-namespaces
    file: ../patches/machine-user-namespaces.yaml
```

</details>

<details>
<summary>And the following <code>kata</code> runtimeClass config:</summary>

```yaml
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata
handler: kata
overhead:
    podFixed:
        memory: "130Mi"
        cpu: "250m"
```

</details>

<details>
<summary>And the following Dagger <code>StatefulSet</code>:</summary>

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: dagger-kata
  name: dagger-kata
  namespace: dagger-2025-01-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dagger-kata
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dagger-kata
    spec:
      containers:
        - image: registry.dagger.io/engine:v0.15.1
          imagePullPolicy: IfNotPresent
          name: dagger-engine
          readinessProbe:
            exec:
              command:
                - sh
                - -exc
                - dagger core version
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 14
          securityContext:
            capabilities:
              add:
                - ALL
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/dagger
              name: data
            - mountPath: /var/run/buildkit
              name: run
      restartPolicy: Always
      runtimeClassName: kata
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1001
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          hostPath:
            path: /var/lib/dagger-2025-01-03-dagger-kata
        - name: run
          hostPath:
            path: /var/run/dagger-2025-01-03-dagger-kata
  updateStrategy:
    type: RollingUpdate
```

</details>

The Engine readiness probe remains in a failed state:

This is what we see in the Engine logs:

```lua
handling http request" client_hostname=dagger-kata-0 client_id=km91rqb1s0f5fnbojtws2reli contentType= method=GET path=/sessionAttachables session_id=v0ssih1jcixhfmep3pf8sda79 span=4deabc5c0c406d3b spanID=4deabc5c0c406d3b trace=67b93a7473490808227f9ac89da2f7a5 traceID=67b93a7473490808227f9ac89da2f7a5 upgradeHeader=
session manager handling conn km91rqb1s0f5fnbojtws2reli" client_hostname=dagger-kata-0 client_id=km91rqb1s0f5fnbojtws2reli session_id=v0ssih1jcixhfmep3pf8sda79 spanID=4deabc5c0c406d3b traceID=67b93a7473490808227f9ac89da2f7a5
handling http request" client_hostname=dagger-kata-0 client_id=km91rqb1s0f5fnbojtws2reli contentType= method=GET path=/v1/traces session_id=v0ssih1jcixhfmep3pf8sda79 span=20f8eaf475f6c0c1 spanID=20f8eaf475f6c0c1 trace=67b93a7473490808227f9ac89da2f7a5 traceID=67b93a7473490808227f9ac89da2f7a5 upgradeHeader=
handling http request" client_hostname=dagger-kata-0 client_id=km91rqb1s0f5fnbojtws2reli contentType= method=GET path=/v1/logs session_id=v0ssih1jcixhfmep3pf8sda79 span=479e9b70c9c80fd7 spanID=479e9b70c9c80fd7 trace=67b93a7473490808227f9ac89da2f7a5 traceID=67b93a7473490808227f9ac89da2f7a5 upgradeHeader=
handling http request" client_hostname=dagger-kata-0 client_id=km91rqb1s0f5fnbojtws2reli contentType= method=GET path=/v1/metrics session_id=v0ssih1jcixhfmep3pf8sda79 span=3929b4c33d566891 spanID=3929b4c33d566891 trace=67b93a7473490808227f9ac89da2f7a5 traceID=67b93a7473490808227f9ac89da2f7a5 upgradeHeader=
handling http request" client_hostname=dagger-kata-0 client_id=km91rqb1s0f5fnbojtws2reli contentType=application/json method=POST path=/query session_id=v0ssih1jcixhfmep3pf8sda79 span=1655157b80e271aa spanID=1655157b80e271aa trace=67b93a7473490808227f9ac89da2f7a5 traceID=67b93a7473490808227f9ac89da2f7a5 upgradeHeader=
load cache for mkfile /schema.json with kjdo6s3m17uxnfgpjdqd9bmci::b4xxiqmostrgdibtlnb8ryd8e"
failed to serve request" client_hostname=dagger-kata-0 client_id=km91rqb1s0f5fnbojtws2reli error="failed to get schema: failed to create blob for introspection JSON: failed to checksum ref: failed to create hash for : operation not supported" method=POST path=/query session_id=v0ssih1jcixhfmep3pf8sda79 spanID=1655157b80e271aa traceID=67b93a7473490808227f9ac89da2f7a5
handling http request" client_hostname=dagger-kata-0 client_id=km91rqb1s0f5fnbojtws2reli contentType= method=POST path=/shutdown session_id=v0ssih1jcixhfmep3pf8sda79 span=fbf2d4222b77404d spanID=fbf2d4222b77404d trace=67b93a7473490808227f9ac89da2f7a5 traceID=67b93a7473490808227f9ac89da2f7a5 upgradeHeader=
main client is shutting down" clientID=km91rqb1s0f5fnbojtws2reli isMainClient=true mainClientID=km91rqb1s0f5fnbojtws2reli sessionID=v0ssih1jcixhfmep3pf8sda79
session manager handle conn done km91rqb1s0f5fnbojtws2reli" client_hostname=dagger-kata-0 client_id=km91rqb1s0f5fnbojtws2reli error="<nil>" session_id=v0ssih1jcixhfmep3pf8sda79 spanID=4deabc5c0c406d3b traceID=67b93a7473490808227f9ac89da2f7a5
removing session; stopping client services and flushing" session=v0ssih1jcixhfmep3pf8sda79
stopped services" session=v0ssih1jcixhfmep3pf8sda79
session removed" session=v0ssih1jcixhfmep3pf8sda79
```

Notice the following error:

```lua
failed to get schema: failed to create blob for introspection JSON: failed to checksum ref: failed to create hash for : operation not supported
```

This error happens in response to `dagger core version`

Here is a side-by-side comparison of `/var/lib/dagger` of a Engine which uses [kata 3.3.0 (left) with `io.containerd.kata.v2` runtime type](https://github.com/siderolabs/extensions/tree/db466d1025443ee0b92aa3410b1b20050f64ada9/container-runtime/kata-containers) vs containerd 2.0.1 right:

<img width="1429" alt="image" src="https://github.com/user-attachments/assets/3f3fed82-67b9-419a-8bae-c5da636882a4" />

<details>
<summary><code>/var/lib/dagger</code> kata 3.3.0 with <code>io.containerd.kata.v2</code></summary>

```lua
/var/lib/dagger/
├── buildkitd.lock
├── cache.db
├── net
│   └── cni
│       ├── 3f18b6h0g9hqyf1jf2io5d1c0
│       ├── 3kigai1pnj3rkwik27spbo82h
│       ├── 4quuvn0lpeezr7c3q44u41aqq
│       ├── 88wii8bxwudm02tzz0elynqbr
│       ├── duq31ynbo6i27owonowcawpmv
│       ├── g7q9taf5tukccflmu5epme3q3
│       ├── gikkztlw44b6xi3ibifwtmqpd
│       ├── iu3wwli740v44hiqc0lsbsj3p
│       ├── j664kh23weoyw8vstwt0cfv1d
│       ├── qj9javf8w99raxdgvcshu20dn
│       ├── qtwgim62ysvxbkbfvtd4t6t13
│       ├── rjmw9sxxfxmudq1gvj2vmv3sx
│       ├── sgkxukyzd3x7g8ikva44ybutn
│       ├── swb39znsmosnnwvtzi2nesste
│       ├── tz1upygzvfbfrk4fvplpdunz0
│       └── ucco1y8ds5i2lx9fdan7d304j
└── worker
    ├── cachemounts
    ├── clientdbs
    │   ├── 40qpieakhvcexp49jbem07tfi.db
    │   ├── 4haudarf27f8skeogc1rsuf5x.db
    │   ├── 4loygqjj1g7sa038nu5ayhkee.db
    │   ├── endzr5ekm823f2tkosng8dl3x.db
    │   ├── k0qq7befk81supfp3p5kdsg7d.db
    │   ├── k1z4opfiqxeg5r9ifmfjjv2s2.db
    │   └── wuqbynablm1ypoa21tvfaz03l.db
    ├── containerdmeta.db
    ├── content
    │   └── ingest
    ├── executor
    ├── metadata_v2.db
    ├── snapshots
    │   ├── metadata.db
    │   └── snapshots
    │       └── 1
    │           └── schema.json
    └── workerid

11 directories, 30 files
```

</details>

<details>
<summary><code>/var/lib/dagger</code> containerd 2.0.1</summary>

```lua
/var/lib/dagger/
├── buildkitd.lock
├── cache.db
├── net
│   └── cni
│       ├── 648zahy58edq4u9qvdl5gqpur
│       ├── 8w2fmwv8f18rlbwx8z1legm7d
│       ├── 9iudnyogaz6u40cq4q3y8wf59
│       ├── ekuz06chz6dphefenugtrq9g2
│       ├── k8plpnocitqk81t0p6sya0k3s
│       ├── khai2wtcqaz3v639e7o6tque1
│       ├── lcay85i9ydaddzm1syqnbdnqx
│       ├── llif85zoagu4hs1w13vy4668w
│       ├── lsfwmqxpe0jw82dthig2jvb64
│       ├── ojnovwmy3zliwjycgo1tb8b3l
│       ├── q1u2br9x9r5zl5zmjaqyn4dji
│       ├── qfzlr3zegjeuc9esb0g3g4id0
│       ├── qo9zvaeuzl3uzfow5qqs7nnap
│       ├── xdumemzrv21j4u1y7xi4qzzvh
│       ├── y4v5zxo71z9tjyd5jyr5wgeeu
│       └── ycrp87hxyyk791pl7xck5ymkz
└── worker
    ├── cachemounts
    ├── clientdbs
    │   ├── 0cpt64v6m38bvzug27qxxc7ki.db
    │   ├── 0g10r42wsdsvhrso6fap83yy2.db
    │   ├── 0lkn28x9ehhhhkdusgc7rcjh1.db
    │   ├── 0prysitk9ughsnfso2z9cgjx5.db
    │   ├── 0t2vkst59zk5locb5c4uy8q36.db
    │   ├── 0vuc94sfqfpo7h9jejnegty16.db
    │   ├── 10k0hobdkaba06ldulhr766oq.db
    │   ├── 1akrjmhcmpxeuze093ratssbq.db
    │   ├── 1z3y1h4beh20edyoyhn1oxmkt.db
    │   ├── 2doqqeu04ih48s25po8ear2wo.db
    │   ├── 2oerd6mlbvf2o8aw1nu2pi910.db
    │   ├── 2sab2mfl6a3pf7hhi5efd633d.db
    │   ├── 2w80a0tink61m0p8tcfov0q9r.db
    │   ├── 358b9kb8qzr2d28kma2iveq78.db
    │   ├── 3jt9v4rfwz1jye8o1gvricdan.db
    │   ├── 3xcm4lzick11ya3e6ijss636m.db
    │   ├── 44d86n5b7k0uhv745l4yf6qu7.db
    │   ├── 4blr6njx9c1sk1pzcadxyl8xh.db
    │   ├── 5jc8eviwdwcuoo62wdsu7kp8j.db
    │   ├── 5na2ptduuiklh66lynq1lx7b5.db
    │   ├── 5p7szrmu0vt7dgxsumlcfovtm.db
    │   ├── 6o9zib2xentjdsaq3hns9bxht.db
    │   ├── 6s6aysgjelyuw9tkserj2a0kc.db
    │   ├── 6vmik6wzb7hhpucx3nm1zz7nx.db
    │   ├── 7ydufn0xjged791eyo8i6o4rx.db
    │   ├── 81btbpdsqa2yaqi3ypzma94wh.db
    │   ├── 8b50lo64os8sx2t8i8f5amg21.db
    │   ├── 8t313a2lvnv7rh03toshvlum8.db
    │   ├── 93m8u1gkelt8nw8d93dpibga0.db
    │   ├── 97rercxxbb8nqleso878jaos5.db
    │   ├── 9cd7jdknhc7vq9wcp9e82v4ro.db
    │   ├── 9fobjavuasft2g5em1lxedoga.db
    │   ├── 9ljjgknj648s4b1ijxdr5mxbq.db
    │   ├── 9mv1nfa1z2wd7d7htbfctvqyz.db
    │   ├── 9o6zg6h643uab7qfvd6sjnigr.db
    │   ├── a72vw1gqvvsnz3d1rogzqzob0.db
    │   ├── b68wr47xq5qqg1jhl77g0fl29.db
    │   ├── bggvqknoznfnt1ho8odl7vslc.db
    │   ├── bjzp0qembty13c96bqfn12bc9.db
    │   ├── bqsukwyp8sl4wpcl49qnkjczy.db
    │   ├── br22kgd81oy6wse9mysx3fl2p.db
    │   ├── cd5sdj0db686lfibjsx4rh3rh.db
    │   ├── cdwqj0y8k9powx2b7lttqg3ka.db
    │   ├── ck6h5ylwch9sv818ueqfaztbu.db
    │   ├── cpcu90flip0tav66z1kei88ks.db
    │   ├── cykg63d5vgeqsah065rht6m6m.db
    │   ├── d16x1cnl9bafi4nua1rsjybv8.db
    │   ├── d3g4382r2lmgnidv69vem6qnj.db
    │   ├── d4jokw17y72l19e2p6cbrmeh3.db
    │   ├── d8bez52k6ni2zvtyezjge8wlw.db
    │   ├── d99izw1vtl9ewth1mn4lihzqr.db
    │   ├── dbklxstjdhz6xr9kdrl46x069.db
    │   ├── ds7nnly9fo2lav00jlnbidq28.db
    │   ├── dxjs5hmfqer2xfnrt79hrtlpl.db
    │   ├── e72oxwb0uztjdrj3oycstuwbx.db
    │   ├── elpfnx7rdrpn76szi71ty9b6v.db
    │   ├── eqz4kaq7u5p1skysze8mllaov.db
    │   ├── ew6tr2fu3wlzlgwdlhqknokqj.db
    │   ├── f09l2gruoxmmkp8v8cg3qarx0.db
    │   ├── fb1p82j29ksuiacyzbnfizqme.db
    │   ├── fc9teotgqzpaag3o80h1945jt.db
    │   ├── fdyc4pdtxllneambo958e35nz.db
    │   ├── fmkpbs5ymd2cccrgtm8ux290j.db
    │   ├── fo35w1lzldvzj58advrptfoo1.db
    │   ├── g0k11rmg1qr882rllhpfq2c1c.db
    │   ├── glv1cu99eaxk769xqqu9dvxjo.db
    │   ├── gntofl3ckyb5wjgbxwnp7q934.db
    │   ├── hb8ea9ub50b2gpjrkzi0h2e77.db
    │   ├── hk4tp5b9clglv3wr0h49tugy1.db
    │   ├── hw79umzj5929bvvpk3orqrlnt.db
    │   ├── hyy7ugywiy1ug3kx63l1eb6tz.db
    │   ├── i2slkhciwm93g007kr56347pu.db
    │   ├── i4rfvrpjxczch0gea0glzguer.db
    │   ├── i5og6wjijc0dl8sb8lizgtiku.db
    │   ├── i90l0csdskyl3aie5pr4p3c91.db
    │   ├── iavomz60439eeeg3zoax751bw.db
    │   ├── icrb7v8kvknbj5lj0ek0i06vx.db
    │   ├── ii9o7j6jwb1j6226zjev2mmun.db
    │   ├── ijnsgaqxessrfrx432x1y7dqf.db
    │   ├── iroswalmc99fi2cnbs4jgaa8c.db
    │   ├── j3lf4khgg99zxcw1o93rf5we1.db
    │   ├── j3rg0aerjm3bw5y8lnq3nuluf.db
    │   ├── j3w3w4efc097k8l2xfvsll2n0.db
    │   ├── jt5txrjrxhp7a2ow20jg0c6dx.db
    │   ├── jx3yd93wphha90kd9z7hwiwd1.db
    │   ├── jzvjzxzljnrh50lb6fouqnwv5.db
    │   ├── k2jd0wm20dyezoc6r8lmsyjuz.db
    │   ├── kmk2t5f6zt3buqt12opom52ai.db
    │   ├── kn2n0r57lv2iznqyr3mteo2v0.db
    │   ├── kogdv9a6iaeqgg6ykam0084qs.db
    │   ├── ks4kwgcxs0iji8f69ug0e8n4t.db
    │   ├── kxsv799tmexj35tp76uvu20q5.db
    │   ├── l1v2eq6hc70xtibdz42ct5gs6.db
    │   ├── l21sx1um7lwo67e6hl0lj71o8.db
    │   ├── l62j37idnjmsgby7dxc6iun2v.db
    │   ├── l8egsgy68pkhqsmb75i104wvh.db
    │   ├── lai84zsq7l5rgq22lws3wk3e7.db
    │   ├── lcdntrap0ceqwisfb68jdjaps.db
    │   ├── ldp1gyixitd5kw3edej61pljk.db
    │   ├── lew74kaovw7pxwjm6o6t9vien.db
    │   ├── liuhnihys9c7p7lnc40kngpli.db
    │   ├── lk58jj3srhvgjlz2a2d7v0cy8.db
    │   ├── lnd130piou1x6pfsu4x6rn8kb.db
    │   ├── lp7sqnibopc3yhullwqjeak13.db
    │   ├── lv8kcl6iai3cqlr3t1kdzfitl.db
    │   ├── m386dt9vc31kbn2dicz9c1rx1.db
    │   ├── mb6ij8w5dn3yairt54blrlada.db
    │   ├── meouneoju5jdnz2uy7alds630.db
    │   ├── mfndxhy3twilk0d3mavn43hk0.db
    │   ├── mgw95drmt6zssj7zh6tstnciz.db
    │   ├── mn7ja5mnj3gm0vynw0svsswli.db
    │   ├── mnuq3ddrq6hqg6fkarqalckm3.db
    │   ├── mv44097mii4ynh89bdes5mc0s.db
    │   ├── mvs8o3rdihhcfagpwyt8zb8z8.db
    │   ├── n6753u08w4p2y050nunkkp41o.db
    │   ├── nf2qacdrgb3qk7tzvlk98ec41.db
    │   ├── nhrnf9waxmbsc3ew4ckebee33.db
    │   ├── nlvfp7j4osmvwnjx0dztuudak.db
    │   ├── nmjxbiccjcoyrk7uedai9cpdt.db
    │   ├── np641dvczca0ccgva94of1mn8.db
    │   ├── nr07ngrq9qjfcpeey3f8dirf9.db
    │   ├── o66x2i9yrmmxt01vj53aghq66.db
    │   ├── o94vgx8160k23rp052y4wkwre.db
    │   ├── ocsf8p7aohcjdp2k2gfdeto40.db
    │   ├── osxoj8sl5xmxaedgjntq68j0h.db
    │   ├── ovjaunry4zsr3pry41ly4uwz2.db
    │   ├── ox0dqhnmx67psm6og7dokp5k1.db
    │   ├── oz9htzn8o271nphv7d3b14fas.db
    │   ├── ozot4xlbzlreyjzr2llfwc2m0.db
    │   ├── p3yjcc4idl0x2lx8y3mk4pzfq.db
    │   ├── pauzx4meo1siat1i1o8vxxqxr.db
    │   ├── pcwon68zidfqkiji4lfwosfcf.db
    │   ├── pdeb1r0c4ov8nf0i3ktpyx133.db
    │   ├── pekt17sbuitq69bj1yvs3af01.db
    │   ├── peorvalylcfcmxen0wlawrx1l.db
    │   ├── ppbk1xw8gyipz04hafqiq7rpe.db
    │   ├── pxwwynzintgpj8rsnrv3bm6a8.db
    │   ├── pya2eb1rttm8qbia6ony8cvin.db
    │   ├── pyet5hvsumblk1huaxpoeswyk.db
    │   ├── q488r4eush94i4re5js903ie5.db
    │   ├── q4kp5ad1l7x8q3a7n97hotbq9.db
    │   ├── q9ro26sh9e1k4bn380pc1dtw2.db
    │   ├── q9x1c9i0y2j9naorrgnnid0oz.db
    │   ├── qc784qcrdjk9ylyhqbt1g6v4b.db
    │   ├── qcwpz3eukp79z4uw67004h8ut.db
    │   ├── qczk42bkmwfydr0dfiglojccp.db
    │   ├── qghbw7ggn2e0gvoydqv2tlzae.db
    │   ├── qhy33i5t1v7qk1jdwi526mhfa.db
    │   ├── qidp72axj2h7d5t7f2omg84ba.db
    │   ├── qjj7sgpcpjxxe7600xbb7cs4a.db
    │   ├── qknw8bwjlg8bcdufmproibiwv.db
    │   ├── qmpvftudxwp445yzmg7k6f20e.db
    │   ├── qns2gir8nmowyms5n9bgw7dpd.db
    │   ├── qns44ex0eu700zk89n0gk2sas.db
    │   ├── qqwmcb0hgovhdcnbkn3dk5ycs.db
    │   ├── qr7rkpx3ift49ptfgojzjnw1w.db
    │   ├── qtuj0k1tmi7ka4j6psdbd2ot2.db
    │   ├── qvehtvegskjcl3zpoq5ll5r9g.db
    │   ├── qxtp7boe8d4svkka5c35j6jc5.db
    │   ├── qyfumluqd4708oduduu16imxd.db
    │   ├── qyhrb0fwat1ltct4vyh0y85i3.db
    │   ├── r025yc8hz214q237sjpgvbmng.db
    │   ├── r1tk5w14qt3r1t58yp24cnwml.db
    │   ├── r2vsq0kye6yqgo4fgak7xfhaa.db
    │   ├── r4c55ksr0x64qiiy8sz309ehi.db
    │   ├── rb273z7zqfmahwm4iyoog67bn.db
    │   ├── rimbuoruvde1a7jgwnlqu1s72.db
    │   ├── rlmex7gburhwzf75b5fxxl9o2.db
    │   ├── rmfm5unkrq98bxwch1r4nk189.db
    │   ├── rqr251z998829kn53t8s8oouq.db
    │   ├── rz8i5ga33xtu3iqif6lx1f0lt.db
    │   ├── rzzz3mmabmsu9h3nxvi44y4ob.db
    │   ├── s0dfmylgz12q5btloyjlu43uo.db
    │   ├── s1objpshfocimsd4sme8mu8bw.db
    │   ├── s5ajpcpu32caozn2nuhg628n7.db
    │   ├── sesvw1iftq17t7rwr380eouc5.db
    │   ├── shfbnpe98ouppx0qefha3t3tq.db
    │   ├── snn8pu39vaj5th6leurzwjugj.db
    │   ├── svisafxoq01r2rr863opg65mx.db
    │   ├── swoxe48p60of1s3nhty8fvwfu.db
    │   ├── t2qsphpab1i8j3ys468axxmup.db
    │   ├── t3pz12cat1cg7b32wif17bfwy.db
    │   ├── t6i4f680iqxwtnrb23ug82tfg.db
    │   ├── t7ft47hy51kmqav89hiihtuj7.db
    │   ├── t7hj6kfwvc0agws1xvyi5f722.db
    │   ├── ta0j16rs5seugfccmcf9t7npx.db
    │   ├── tbuohnpjij5iiuhez34hneh80.db
    │   ├── tci48o6l32ylkrpb3i2s2dn1f.db
    │   ├── tn3gpx3trd8zntc0h7tjlk9r3.db
    │   ├── tsc9l8p56tdpvo9rlt3t4vv65.db
    │   ├── tx2ta85jmgszsaq1cmy8zy552.db
    │   ├── u9wceob0e9gaalzcez4i517zj.db
    │   ├── ub4651fr7gg47f37d2vjzrdij.db
    │   ├── ucxj0czc4tcekplyk5ct4pc1z.db
    │   ├── ug4m65yrdx18jow41jvns5nnn.db
    │   ├── uja7q1pcff5b7in85g7emsn24.db
    │   ├── uyz3rdqb5axobxybbiejcfu67.db
    │   ├── v1bjkvm2hi3497c4lhlnc3ut8.db
    │   ├── v3h5zij0jlhtbjapp19lduor1.db
    │   ├── v5plcamgzetp0l6stsqiua1qa.db
    │   ├── vd12ihw3dmt4b0gc95fx75fhh.db
    │   ├── vegkyeyzt2ufz7bb3pd51aimo.db
    │   ├── vla0stiyr4z38o6ghl3d2cgyx.db
    │   ├── vr9ivipeg4gou1m4iayrukzmf.db
    │   ├── vveuisem41hpyffo2exjd0t1a.db
    │   ├── vzxjzcr7p4hiez42lxf9lifoq.db
    │   ├── w4dbi6rifu1tpb0co2soz1i4o.db
    │   ├── w5has8gaui5ae1ltyf6u25wmb.db
    │   ├── wcybr84yltpatca0rftrb9a4v.db
    │   ├── wex8e1k1v141qugqafmgnbs59.db
    │   ├── wh4n1vaob0ldmebg5mypkzc75.db
    │   ├── whrrv3olhr4ag8hw7ytft41nk.db
    │   ├── wile513xlv4jegsfzllex2amc.db
    │   ├── wnwy24glfahum9vpb2k22a0be.db
    │   ├── ws8imy6btjedv30klr5msecn3.db
    │   ├── wu502zclzirfgwl4f6bm896bw.db
    │   ├── wuinnjuiujwb9zho4ollyn6wo.db
    │   ├── wy8wwogbp6ymk3jf7krmc65d4.db
    │   ├── x06kl8n6pi0pnx5stz2itp36n.db
    │   ├── x4naecp19ip6kb795vv027btt.db
    │   ├── x7dujfqnk096rtzh81hh82uar.db
    │   ├── xaitrxnq1z4vsuzp1shltylkw.db
    │   ├── xfz13wjismcigtj0kou456st5.db
    │   ├── xmaoqxelrllb8augu5dwsjuc7.db
    │   ├── xo363purka9tyo6zfqg457lb5.db
    │   ├── xshxe3k2103ptj5ahj1mlvia7.db
    │   ├── xsou1x8sukggm1yf1g08n1tsq.db
    │   ├── xy2bj204zuu19zsf3y7208cuv.db
    │   ├── xylbwa6jla7u8fxj0gqqab8rq.db
    │   ├── y2bd34nrr0w5clxyhdc08jiaz.db
    │   ├── y4f5ko4wgwz592ri6309o9rs1.db
    │   ├── y673w239aemcghdfvest3v7rd.db
    │   ├── yatkwmliupy11vyr59lzkyele.db
    │   ├── yf2a8ldaf3lykbiulub8fprvu.db
    │   ├── yul0zpmhj1axdr0bg5la6ovup.db
    │   ├── yx789wi4438251rxlsogzap8u.db
    │   ├── yz0t9e094pbb59dqvtk8bjsa5.db
    │   ├── yzs8ng3w3xy70q9dopb8kpi0a.db
    │   ├── z3ev6c67jz0mqi6p7lstt4wbf.db
    │   ├── zdykll77x35d3aehqgl5ooqaw.db
    │   ├── zeqgzjf5ur2eed480npyfi8jt.db
    │   ├── zmtk16q3ijj3vhx6ma076e7dh.db
    │   ├── zxa0gqymd16l93uarmj62r63m.db
    │   ├── zyq7dksi066wbmb7cko7nu30b.db
    │   ├── zzgyv4r1ch8mdkxdylp2bfy3g.db
    │   └── zzwcowqvjn3khfkfx5xxxai6m.db
    ├── containerdmeta.db
    ├── content
    │   └── ingest
    ├── executor
    ├── metadata_v2.db
    ├── snapshots
    │   ├── metadata.db
    │   └── snapshots
    │       ├── 1
    │       │   ├── fs
    │       │   │   └── schema.json
    │       │   └── work
    │       └── 3873
    │           └── fs
    └── workerid

15 directories, 269 files
```

</details>

What I find interesting is that even if we don't use a volume, we still see the same issue. This makes me suspect that there is an issue between kata & Dagger's use of overlay-filesystem. This is my best lead so far:
- https://github.com/kata-containers/kata-containers/issues/2474

Will continue digging. If you have a thought that might be helpful, please share it in the comments below.

---
Learned about this behaviour part of:
- https://github.com/dagger/dagger/pull/9309
